### ISSUE TITLE
exception: U_INVALID_CHAR_FOUND

### ISSUE THREAD

**Issue by douknoukkem** [MusicPlayerDaemon/MPD#118]
Weird tags or filenames will leave MPD unresponsive and require kill -9. The first two files (vaporwave) has tags/filenames that are intentionally as weird as possible. The third one is relatively normal. They also happen to all be in zip files. I just need it to not freeze.

I'm pretty sure the first two files are public domain, so I'm going to link them here:
https://a.doko.moe/iqjcub.zip
https://a.doko.moe/urlqwr.zip

[log.txt](https://github.com/MusicPlayerDaemon/MPD/files/1337586/log.txt)

Sep 25 23:35 : playlist: queue song 1:"notanime/vaporwave.me/TRVCXR/TRVCXR - ＤＲＥＡＭ ＭＡＬＬ おやすみなさい 2 0 0 1/TRVCXR - ＤＲＥＡＭ ＭＡＬＬ おやすみなさい 2 0 0 1.zip/TRVCXR - cqd`l l`kk ₷݂Ȃ 2 0 0 1 - 02 v ` x M͂ǂȂƂꏏł.flac"
Sep 25 23:35 : exception: U_INVALID_CHAR_FOUND

Sep 26 01:53 : playlist: queue song 1:"notanime/vaporwave.me/bl00dwave/bl00dwave - ＳＥＡ ＶＩＢＥＳ/bl00dwave - ＳＥＡ ＶＩＢＥＳ_mp3.zip/bl00dwave - rd` uhadr - 07 r.mp3"
Sep 26 01:53 : exception: U_INVALID_CHAR_FOUND

Sep 27 08:16 : playlist: queue song 1:"high-res/umbrellafactor/[umbrellafactor] (Hi-Res) LiSA - LUCKY Hi FiVE! (FLAC 24bit／96kHz).zip/[umbrellafactor] (Hi-Res) LiSA - LUCKY Hi FiVE! (FLAC 24bit^96kHz)/2-0007147048.4608.flac"
Sep 27 08:16 : exception: U_INVALID_CHAR_FOUND

**Comment by MaxKellermann** [comment]
btw. I did some research on why the file name is broken in the first place - it turns out that your ZIP file encodes the file names in an encoding that is unknown to be - it's not UTF-8 (Unicode). In addition, each file name has an "UnicodePath" (0x7075) entry with the same name encoded in UTF-8. However, the zziplib library used by MPD does not know this extension and ignores it silently.
