### ISSUE TITLE
enhancement: systemd service type to idle/simple

### ISSUE THREAD

**Issue by holytrousers** [MusicPlayerDaemon/MPD#121]
hello 
i have had mpd set up to start as a user service for a long time and i found out that the **mpd.service** _Type_ was set to _notify_, which made my login hang for a considerable amount of time ( large database )
Is there any reason to wait until mpd starts because setting it to **idle** greatly enhanced my experience ?
thanks for this great piece of software !

**Comment by MaxKellermann** [comment]
Yes.

Side note: I think you should rather find out why your login is delayed. There is no reason why it should be, unless you configured a dependency on MPD. But since this is not a MPD problem but a systemd configuration problem, this is not the place to get help with your problem.

Now about your feature request: it is wrong. You can find out why it's wrong by reading systemd documentation:

> Note that this type is useful only to improve console output, it is not useful as a general unit ordering tool

It means by switching to `idle`, you abuse this service type to get a random side effect of it.

**Comment by holytrousers** [comment]
My login is delayed because i enabled the --user mpd.service which starts after i log in ( i use tty ) so i have to wait a few seconds before mpd finishes loading to get my prompt. 
Setting Type in mpd.service to **either** simple or idle fixes that; simple being the obvious choice here i wondered why you chose to set it to notiy ( notify forces systemd to wait until mpd sends a notification message and then exits )
As to why i am talking about it here : i found that you were hosting the systemd files (user/system) so i thought they were responsible for the ones installed by my distro.
Thanks again for explaining me if i'm doing something wrong.

**Comment by MaxKellermann** [comment]
No, neither `idle` nor `simple` "fix" that. They just make the problem invisible, but the change is incorrect. It is incorrect because it makes systemd believe that MPD is operational right from the start, but it's not. The `notify` setting is for daemons which are capable of telling systemd when they're really becoming operational, and MPD can do that.
If you don't want to investigate how to optimize this properly, you can just use an override, but MPD's vanilla unit file will not be changed, because the change you propose is wrong.

**Comment by holytrousers** [comment]
i understand your point.
 so my problem seems te be in the way systemd starts services and there maybe a way to run mpd.service parellel or after login ( though i'm still investigating and haven't found anything relevant yet )
thank you i will let you know if i found the solution !

**Comment by ArchangeGabriel** [comment]
@MaxKellermann As a matter of fact, I was going to ask for a similar change. But since my reasons differ I’m opening a new issue about this: #124.
