### ISSUE TITLE
Error while starting mpd 

### ISSUE THREAD

**Issue by Mangeshrex** [MusicPlayerDaemon/MPD#1217]
After putting my configurations i was getting a very weird issue when starting mpd tried to search over google but there was no relevant fix for my error. The error is : 
`mpd: symbol lookup error: mpd: undefined symbol: mpg123_info2` 

 My config 
https://termbin.com/n3iy

**Comment by MaxKellermann** [comment]
This is a problem with a broken library on your system, and has nothing to do with MPD.

**Comment by Mangeshrex** [comment]
can you tell what could be the broken library? or any hint on how to find the broken lib?

**Comment by MaxKellermann** [comment]
No, not if I wanted to (I don't want) - because I have no information about your computer. I don't even have any information about your MPD installation, not even your MPD version number - because you decided to delete the bug reporting template, and decided not to post anything, even though you were asked to. So even if this bug report were about MPD, I would have closed it because of your refusal to cooperate.
