### ISSUE TITLE
MPD keep on receiving uninterruptible sleep signal(D) after sometimes

### ISSUE THREAD

**Issue by tcheukueppo** [MusicPlayerDaemon/MPD#1260]
### Description of the bug
The song stops playing at a certain point when it receives the uninterruptible sleep signal then continues playing upon release, I was doubting if this can happen because my disk can be very slow, then decided to play those songs on cmus and audacious and I got nothing wrong. I'm playing .flac files if this can help.

### What I should expect from MPD
it should play my songs just fine :)

### Music Player Daemon 0.22.6 (0.22.6) installed on debian from the bullseye source.

Thanks

**Comment by MaxKellermann** [comment]
First of all, version 0.22.6 is unsupported because it is 5 bug-fix releases behind.
Second, you deleted vital parts of the bug reporting template. You expect me to help you with your problem, while at the same time refusing to post the information you were asked to provide.
Third, I don't understand the problem. What is an "uninterruptible sleep signal"? How do you "release" it?

**Comment by MaxKellermann** [comment]
The log you copied shows that you did not start playback.
I don't think this bug report is going anywhere. I don't have time to keep asking questions until you provide enough information. And since your MPD version is old and unsupported, and you did not update it, it's pointless to analyze further. Sorry, but I can't help you.
