### ISSUE TITLE
Segfault on malformed flac file during database update

### ISSUE THREAD

**Issue by hiqua** [MusicPlayerDaemon/MPD#133]
Hi,
I have a malformed (partially downloaded) flac file on which mpd segfaults at every database update, instead of skipping it.

From the backtrace, I understand that `DivideString` is called with a null pointer, which is directly passed to the `strchr` function without any check. The null pointer is `comment` which is defined in the `flac_scan_comment` function.

This is the backtrace from gdb:
[gdb_backtrace.txt](https://github.com/MusicPlayerDaemon/MPD/files/1404788/gdb_backtrace.txt)

The segfault happens with the mpd version in debian stable and unstable, as well as the master version of this repository as of today.

Let me know if you need more information.

**Comment by MaxKellermann** [comment]
Sorry, this is a libFLAC bug. `FLAC__StreamMetadata_VorbisComment_Entry` is guaranteed to not contain `NULL` values according to https://xiph.org/flac/api/structFLAC____StreamMetadata__VorbisComment__Entry.html
.. because there is an explicit guarantee for the "trailing NUL character", which implies the pointer cannot ever be `NULL`. Also the `strlen(entry)` example code would be illegal with `entry==NULL`.
This bug must be fixed in libFLAC.
