### ISSUE TITLE
Global volume changes on enable/disable outputs

### ISSUE THREAD

**Issue by tmp6154** [MusicPlayerDaemon/MPD#1423]
### Describe the bug

I run source-compiled MPD 0.23.5 on Gentoo Linux, but this has been a long-standing issue for as long as I've been running MPD. This might have something to do with software mixer, since all of affected outputs use `mixer_type "software"`. It's possibly related to issue #189, but not only restricted to alsa outputs, but also to e.g. fifo outputs, connected to snapcast. Still, software mixing is present in this issue, so it seems to be common denominator between two issues.

1. I set volume to 63.
2. I disable output 3.
3. I set volume to 88.
4. I enable output 3.

## Expected Behavior

Volume stays at 88. All outputs should sound as intended on volume 88.

## Actual Behavior

Volume falls to 83. Output 3 sounds quiet, like on volume 63, while all other outputs seem to continue playing at volume 88.

## Some thoughts on this.

This wouldn't be much of a problem, but I have scripts for smooth adjustment of volume that gradually increase/decrease volume by 1 in fixed intervals (to make volume change more comfortable or to gradually turn off music during falling asleep). They rely on `mpc volume` reporting correct volume, however, changing outputs not only modifies global volume (confusing the scripts), but it's also incoherent, because all outputs play at their last known volume. However, setting a volume after changing outputs seems to properly set volume for all enabled outputs. Since MPD doesn't have per-output volume controls, this really seems to be a bug in software mixing.

What seems to happen - is global volume (after output changes) being set to average of outputs last known volumes. That's because I have 6 outputs configured. And

((88*5)+63)/6 = 83,8333333333

Probably, MPD floors this value down to 83 and sets it as "global" volume, while all outputs really just continue running on their respective volumes.

As a workaround - I've made a couple of bash functions, that replace `mpc enable` and `mpc disable` functionality, by saving current volume into variable, changing output status and re-setting volume back to saved value afterwards.

```
mpdenable() {
    local MPDVOL=`mpc volume | grep -oP "\d+"`
    mpc enable $1
    mpc volume $MPDVOL
}

mpddisable() {
    local MPDVOL=`mpc volume | grep -oP "\d+"`
    mpc disable $1
    mpc volume $MPDVOL
}
```

Most likely, a proper fix for this would be to set enabled output volume to current global volume, not to recompute global volume as an average of individual outputs volumes.

## Version

```
Music Player Daemon 0.23.5 (0.23.5)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple

Storage plugins:
 local udisks

Neighbor plugins:
 udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [fluidsynth] mid
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [pcm]

Filters:
 libsamplerate

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa openal httpd

Encoder plugins:
 null vorbis opus lame wave flac

Archive plugins:
 [bz2] bz2

Input plugins:
 file io_uring archive alsa curl ffmpeg

Playlist plugins:
 extm3u m3u pls flac cue embcue

Protocols:
 file:// alsa:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mmsh:// mmst:// rtmp:// rtmpe:// rtmps:// rtmpt:// rtmpte:// rtmpts:// rtp:// rtsp:// rtsps:// srtp://

Other features:
 dbus udisks epoll icu inotify ipv6 tcp un
```

**Comment by tmp6154** [comment]
Yes, after doing code diving in `Volume.cxx` and `MultipleOutputs.hxx`, this turned out to be exactly what I thought - global volume gets calculated as an average of all software mixers.

https://github.com/MusicPlayerDaemon/MPD/blob/946cf25732c05639802f4f6d3f94d1ea1adec160/src/output/MultipleOutputs.hxx#L134-L139

But as long as there's no real way to control individual mixers via mpc, this doesn't seem to be really correct way of handling 
global volume.

**Comment by MaxKellermann** [comment]
You are right, MPD only knows one global volume level for all "outputs which have a mixer". That's by design (or: nobody cared enough to implement per-output volume controls and wire it to the protocol).
Knowing this, what's the bug?

**Comment by tmp6154** [comment]
It just doesn't feel right that enabling output keeps it's last volume level when it was enabled, rather than setting it to match other outputs (global volume). That is, I think that setting volume should affect disabled outputs volume, as well as enabled ones.

If that's by design - OK, just found it pretty weird quirk that enabling outputs changes volume (due to averaging) but mixers could play at different levels (while it not directly supported).

Of course, this "bug" could be exploited to achieve per-output volume control (but in a pretty awkward way). Like

Disable all outputs but output 1
Set volume to desired volume for output 1
...
Disable all outputs but output N
Set volume to desired volume for output N
Enable all desired outputs

And then all enabled outputs will play on different volumes, effectively giving per-output control. But without direct support in protocol it's pretty awkward due to need to disable/enable outputs, which would cause audio stutters, making it hardly useful as a feature.

**Comment by MaxKellermann** [comment]
Yes, it's weird, but any other way would be just as weird, just a different kind of weird. The reason why it's this way is not exactly "by design", it's just what was there initially/historically, and nobody came up with a better design.
> I think that setting volume should affect disabled outputs volume, as well as enabled ones.

That would be weird in a differend way - somebody could use "alsamixer" to manipulate a device, and then enable it in MPD, which would suddenly revert the change made by "alsamixer". No matter which way you implement - 50% of the MPD population would believe it's bad ...

Since there are no per-output volumes (yet), there's no proper way to do it.
And even if there were per-output volumes, you'd still need to decide whether MPD should have "full control" or whether it should be possible to use external tools like alsamixer.
Now think of other output plugins - like PulseAudio or PipeWire - where the sound server would like to have primary control over volumes, and remembers MPD's volume setting, because the primary volume knob would be that sound server's central mixer.
Any design choice in MPD would need to be compatible with any plugin, and MPD's problem space (and user space) is very diverse.

**Comment by tmp6154** [comment]
Agreed, you raise a good point about hardware mixers and/or sound servers. Didn't think about it that way.

But still, for setup with _software_ mixers, wouldn't it be better to set all _software_ mixers to same volume and keep them in sync (at least, until/if per-output volume control is wired to the protocol)? After all, software mixers exist only within MPD itself and wouldn't affect system volume. Even if they technically support being set to different values - this is not officially implemented (yet?) and possibility to get them out of sync by output enable/set volume/disable chains is not even documented (that's one reason why I considered this quirk to be a bug).

Moreover, I can hardly imagine that such change to software mixing would be considered bad by anyone from MPD user base. I mean, only use case for current behavior I can imagine is if someone has also found this quirk and used it to implement scripts to do per-output volume control via it. Then keeping all software mixers volume in sync would break them. Still, since it's an implementation quirk rather than proper per-output volume support, it would be brittle (any change of volume through MPD clients would break this and set all mixers to same level, restricting the volume changing to be done only from such hypothetical scripts), cause playback artifacts (due to enabling/disabling outputs), etc. So I really doubt that someone uses this undocumented quirk in practice.

So, the only downside I see is that it would need adding a special case to check if output has software mixing and if it does - set it's volume even in disabled state.

**Comment by MaxKellermann** [comment]
Yes, always applying volumes to software mixer sounds reasonable. I thought it would work that way already, but apparently it doesn't.

**Comment by MiMtmassey** [comment]
Oh the irony…

I reported this 4 years ago, when I was told that I was both wrong and crazy, even after I outlined the procedure exactly like was outlined here and in the commit.  In that time, I’ve reworked my flow to work with this, and in doing so, I used it exactly like tmp6154 described: a poor-man’s separate output volume control.

And *now* it’s changing. I agree that the way it worked before was crazy and has undesirable effects; but the problem is, there’s now no way to actually maintain separate volume levels for each output!  I’ve now very much made this something I depend on:  mute all other outputs, adjust volume, unmute the other outputs.  It’s a hassle, but at least I can have a loud volume in my garage without blasting out my wife in the kitchen.

The right way to address this is per-output volume control; however, could it be possible to at least keep the old way of working as a configuration option until then?

**Comment by tmp6154** [comment]
Well, it's still possible to have separate external volume knobs (e.g. with snapcast or via pulseaudio knobs). I believe it's also should be possible with ALSA, though it's more complicated to configure, because you'd have to define a separate mixer in asoundrc and have MPD to output to such device. This is how I'm controlling relative room volume currently (while using MPD's volume knob as "absolute" value).

I've ended up not using this bug to do per-output volume control, even though it was temping to do so because I change volume frequently and even have made various scripts to change volume smoothly. So it both made this bug more prominent for me (since volume changes and output toggling was quite frequent) and made it more difficult to successfully use the bug (I have 6 outputs configured, so just going through them in enable/disable cycle to change per-output volumes was too noticeable, unpleasant and made it almost impossible to implement smooth volume change while keeping separate volume levels).

Indeed, the better way would be a proper per-output volume control (at least, for software mixers). It would be more convenient to control both per-output volumes and master volume from one place and simplify the scripting around the volume control. Generally, as proven by this bug, MPD supports per-output volumes just fine, it's just not properly wired to the protocol as a separate command.

Though, if you're using Raspberry Pi with default build of MPD from Raspbian - then I think you have nothing to worry for years to come. After all, this fix is not even included in any released MPD version yet (perhaps, it will be in 0.23.7?). Even in Debian Bullseye, shipped MPD version is 0.22.6. So the fixed version would probably come in Debian 12, somewhere in late 2023. So, by the time this fix gets shipped in Debian-family distros, there's even chances that someone will implement proper per-output volume support in MPD.

**Comment by MiMtmassey** [comment]
Yeah, I agree about the rough edges both ways.  Either way, someone loses something.  I experienced that loss then: turning on an output that had previously been disabled while loud would again be loud, and make my wife unhappy — which is why I wrote the bug report then.  Of course 4 years ago I wasn’t yet using the unintended side-effect, and now I am! :)  And I also agree it’s not invisible: it’s annoying to interrupt playback in a room because I need to change the volume in a different room.  But it actually *works*.  (And no: manually managing external mixers somehow in yet another interface is *not* an option: I need normal people to be able to use this…)

That’s the irritating part: MPD does indeed handle  separate volumes for outputs just fine. It just needs to be exposed! :)

Given the total dismissal I received last time using the Debian version, I switched to a compiled version.  Of course, I was *still* totally dismissed, so I’m not sure it matters.  I also now use Fedora on the Pi, so I do stay a little closer to mainline.

Likely I’ll have to stick with compiling the code after reverting that commit. :(  Unless someone has mercy on me and makes it a configuration option, though I’m not holding my breath.

I would love to hold my breath for separate volume management, but I’m sure I’d pass out first. :)

**Comment by MiM-TMassey** [comment]
Well, it's happened.  Fedora updated to MPD 0.23.7, and I've lost separate volume control of outputs.  I realize that this is a bit like https://xkcd.com/1172/ (after all, I originally reported it as a bug myself 4 years ago!), but I am absolutely depending on that behavior now.  Independent volume control on outputs is such a *glaring* missing feature, and it's very painful to not have it any more.

For now, I'm going to have to dnf downgrade mpd-0.23.6 mpd-firewalld-0.23.6.  But I also wanted to add one more plea for *some* way of independent output volume control.
