### ISSUE TITLE
Add Support for MusicBrainz Artists Tag

### ISSUE THREAD

**Issue by TehTotalPwnage** [MusicPlayerDaemon/MPD#150]
It looks like by default, MPD depends on the usual artist tag found in most audio files in order to determine the artist for a track. However, the artist tag looks like it's currently just being read as a string. This can cause the music library to look relatively disorganized as seen here:
![selection_037](https://user-images.githubusercontent.com/4282201/32737649-80f94f80-c84f-11e7-8ad0-2c4ac685ca3f.png)
MusicBrainz provides a separate "ARTISTS" tag that divides the list of artists into separate items, which if implemented correctly, could alleviate this mess of an artist list. Kodi has already implemented it in their software with [this PR](https://github.com/xbmc/xbmc/pull/7281).

Though I know the developers might not be open to parsing more tags, considering that the MPD database already reads the MusicBrainz "ARTISTID" tag, I think it would make sense to allow for support of the "ARTISTS" tag and fall back to the default artist tag elsewhere.

**Comment by MaxKellermann** [comment]
Why is this tag necessary? MPD can read multiple distinct `ARTIST` tags very well. The real problem here is that your music files contain just one `ARTIST` tag with all of the artists squeezed into one single string, instead of having multiple `ARTIST` tags, one for each artist. This is bad input data, and not a missing MPD feature.
Maybe it would be easier to discuss this had you provided a link to the official specification of that tag.

**Comment by TehTotalPwnage** [comment]
I didn't mean to imply that it was a missing feature, sorry about that! I meant to suggest that MPD might benefit from being able to read the MusicBrainz artists tag.

It's just personal opinion on whether to include the tag to be honest. I suggested this tag based on the fact that MusicBrainz and their application, Picard, use the tag in order to help divide artists for players to be able to better organize their libraries. They alternatively use the ID3 `ARTIST` tag specifically for providing a display name for players such as MPD to broadcast in the Now Playing information of a track, and [it seems unlikely they'll move away from this in the near future.](https://tickets.metabrainz.org/browse/PICARD-586)

It's granted not an official ID3 specification, but Kodi has [already implemented support for this tag in version 16.0](https://github.com/xbmc/xbmc/pull/7281). In the meantime however, I don't think it's the best idea to rely solely on distinct `ARTIST` tags, considering it's not even part of the ID3 specification. ID3v2.3 [uses '/' as a delimiter](http://id3.org/id3v2.3.0#Text_information_frames) for strings while ID3v2.4 appears to [use a null byte as a delimiter](http://id3.org/id3v2.4.0-frames). 

Considering that the use of multiple `ARTIST` tags is also an unofficial specification, it might also be worth supporting the Artists tag. Of course, it's up for discussion how widely Artists is used and whether it warrants implementation in MPD.

**Comment by MaxKellermann** [comment]
I agree with that Picard bug report. What Picard does looks like an unnecessary proprietary tag, when the same thing can already be done with standard ID3. Therefore, it's badly designed. Maybe the Picard developers weren't aware that this is already possible with ID3.
I don't want to promote bad and unnecessary designs. Therefore, MPD will not support this proprietary tag, and instead support standard ID3.
People should better urge the Picard project to follow the standards as well, instead of inventing new proprietary ones.
