### ISSUE TITLE
MPD crash after running for a few hours. 

### ISSUE THREAD

**Issue by jovianArchiver** [MusicPlayerDaemon/MPD#1508]
### Describe the bug
MPD Crashes after running for a few hours without issue.

## Expected Behavior
MPD shouldn't crash.

## Actual Behavior
MPD Crashes.

## Version

Music Player Daemon 0.22.6 (0.22.6)

## Log

Apr 05 16:30 : avahi: Initializing interface
Apr 05 16:30 : exception: RTIOThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted
Apr 05 16:30 : avahi: Client changed to state 2
Apr 05 16:30 : avahi: Client is RUNNING
Apr 05 16:30 : avahi: Registering service _mpd._tcp/Music Player @ cluster-head
Apr 05 16:30 : avahi: Service group changed to state 0
Apr 05 16:30 : avahi: Service group is UNCOMMITED
Apr 05 16:30 : state_file: Loading state file /home/pi/.config/mpd/mpdstate
Apr 05 16:30 : playlist: queue song 87:"Astrophysics - apathy/Astrophysics - apathy - 01 oneironaut.mp3"
Apr 05 16:30 : avahi: Service group changed to state 1
Apr 05 16:30 : avahi: Service group is REGISTERING
Apr 05 16:30 : decoder_thread: probing plugin mad
Apr 05 16:30 : decoder: audio_format=44100:24:2, seekable=true
Apr 05 16:30 : exception: OutputThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted
Apr 05 16:30 : output: opened "stream" (shout) audio_format=44100:f:1
Apr 05 16:30 : output: converting in=44100:24:2 -> f=44100:24:2 -> out=44100:f:1
Apr 05 16:30 : exception: OutputThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted
Apr 05 16:30 : output: opened "my_fifo" (fifo) audio_format=44100:16:2
Apr 05 16:30 : output: converting in=44100:24:2 -> f=44100:24:2 -> out=44100:16:2
Apr 05 16:30 : exception: OutputThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted
Apr 05 16:30 : output: opened "fake out" (null) audio_format=44100:24:2
Apr 05 16:30 : avahi: Service group changed to state 2
Apr 05 16:30 : avahi: Service 'Music Player @ cluster-head' successfully established.
Apr 05 16:31 : decoder_thread: probing plugin mad
Apr 05 16:31 : mad: detected LAME version 3.99 ("LAME3.99r")
Apr 05 16:31 : mad: LAME peak found: 0.000000
Apr 05 16:31 : mad: LAME track gain found: -9.000000
Apr 05 16:31 : mad: encoder delay is 576, encoder padding is 1201

[ ... Lots of playing music here ]

Apr 06 05:50 : decoder_thread: probing plugin sndfile
Apr 06 05:50 : decoder: audio_format=44100:16:2, seekable=true
Apr 06 05:50 : output: converting in=44100:16:2 -> f=44100:24:2 -> out=44100:f:1
Apr 06 05:50 : output: opened "fake out" (null) audio_format=44100:16:2
mpd: ../src/player/Thread.cxx:812: void PlayerControl::PlayChunk(DetachedSong&, MusicChunkPtr, const AudioFormat&): Assertion `chunk->CheckFormat(format)' failed.

**Comment by skidoo23** [comment]
Generic answer ist https://www.musicpd.org/help/ - please update your MPD to recent version. If error persists post a backtrace. https://mpd.readthedocs.io/en/stable/user.html#mpd-crashes

**Comment by 1985a** [comment]
I've experienced this kind of issues and now here one of them cause never debugged it. I hope this is the one.
Furthermore, I can't copy from the terminal directly, due to my windows manager, so i take two pictures in order to allow you to see.
[pictures](https://imgur.com/a/ocMjlaG)

Below is my conf file.

`
music_directory        "~/Music/"
playlist_directory     "~/.mpd/playlists"
log_file	"/dev/null"
pid_file        "~/.mpd/mpd.pid"
state_file        "~/.mpd/mpdstate"
mixer_type "software"

audio_output {
type "alsa"
name "ALSA"
device "hw:0"
tags "yes"
}

audio_output {
type "shout"
encoder "opus"
name "From the house"
port "25646"
mount "radio"
host "XXXXXX"
protocol "icecast2"
password "XXXXXXXXX"
description "my cool stream"
bitrate "auto"
format "48000:16:2"
opustags "yes"
}
decoder {
plugin "gme"
accuracy "yes"
enabled "yes"
}
decoder {
plugin "mikmod"
loop "yes"
}
decoder {
plugin "modplug"
loop_count "4"
}

input_cache {
    size "1 GB"
}

resampler {
plugin "soxr"
quality "very high"
}
playlist_plugin {
name "m3u"
enable "true"
}
bind_to_address "127.0.0.1"
port "6600"
database {
plugin "simple"
path "~/.mpd/mpd.db"
compress "yes"
cache_directory "~/.mpd/cache"
}
`

**Comment by MaxKellermann** [comment]
Your MPD version is old and unsupported.
