### ISSUE TITLE
artefacts of soxr resampling

### ISSUE THREAD

**Issue by mistepien** [MusicPlayerDaemon/MPD#153]
My DAC is 96/24 capable so eg. files 192/24 files or dsd64 wavpacks need resampling.
In case of switching between two dsd64 files or between two 192/24 files there is audible "glitch".
It is related both to mpd-0.20.11 and mpd-git.

**Comment by MaxKellermann** [comment]
This doesn't appear to make sense, but maybe because information is missng: MPD (and libsoxr) cannot resample DSD. Please clarify.
Many glitches reported here are caused by badly designed DACs when switching between audio formats. This can be worked around by forcing MPD to use a fixed audio format, however the conversion is lossy.

**Comment by mistepien** [comment]
Soxr and mpd can resample because audible glitch is only at the very beginning of track of switch. In other words, the moment of switch is coupled with glitch, meanwhile nothing like that happens in case of eg. 44.1/16 files.

**Comment by MaxKellermann** [comment]
Nothing in your reply clarifies anything.

**Comment by mistepien** [comment]
all I want to say: MPD can resample DSD.

**Comment by MaxKellermann** [comment]
I'm pretty sure it can not. But please prove it - show me the code which does that. You'll find out that all of the resampling code was written by me, so I'm kind of an authority here.
