### ISSUE TITLE
Recently added album

### ISSUE THREAD

**Issue by inquisition** [MusicPlayerDaemon/MPD#172]
I need a way to get recently added albums from my MPD Server. A list of recently added albums (10, 25 or 50 albums) sorted by add to DB date.

**Comment by MaxKellermann** [comment]
MPD doesn't remember when files were added to the database. It does however know when a file was last modified. Would this be good enough for you?

**Comment by inquisition** [comment]
This is not the perfect solution but still it is better than nothing. Thanks !

**Comment by kowalcj0** [comment]
To whoever it may concern, here's a handy bash command alias to find all tracks that were modified since a specific date: (it basically provides `"Recently added"` functionality)

```shell
alias recent="mpc -q clear && mpc -q searchadd \"(modified-since '$(date -I -d '-1 month')T00:00:00Z')\" && mpc -q play"
```

**Comment by rien333** [comment]
> MPD doesn't remember when files were added to the database

This is one thing I really miss, since it keeps you from forgetting about new entries to your collection, especially if you got a nice GUI for doing so. In fact, I set most of my music players to "Sort by added" when possible. Other projects, such as [`beets`](https://github.com/beetbox/beets),  do actually keep track of this sort of metadata in their database.

 So, is keeping track of this metadata really outside of the scope of mpd? I know that this feature has been [requested](https://discourse.mopidy.com/t/mopidy-mpd-sort-albums-by-date-added/3926/8) [for](https://github.com/CDrummond/cantata/issues/682) [some](https://github.com/SoongNoonien/mpdevil/discussions/66) frontends, and I can't imagine it adding a whole lot of complexity.
