### ISSUE TITLE
Allow removing items from database

### ISSUE THREAD

**Issue by valrus** [MusicPlayerDaemon/MPD#1735]
Due to tweaking my music organization strategy I often find myself with duplicate albums in my MPD database. As far as I can tell, the only way to remove them is to wipe the whole database and `update` from scratch. Is it possible to add a way to remove items from the database in a more targeted way?

**Comment by MaxKellermann** [comment]
> only way to remove them is to wipe the whole database and `update` from scratch

What the...? You never have to wipe the database. If you do that, and then update, the songs will reappear, of course, because the files are still there.

MPD will only not pick up those songs if you remove the files. And then, a normal `update` (without wiping) will notice that the files are gone and remove the entries from the database.

**Comment by valrus** [comment]
The situation I have is that I add an album to the DB, then make some modifications to the files and update to add it again. (I don't remember what exactly I did, and I will try to get a simple repro in the future.) Then the album appears in the DB twice and is duplicated if I use `mpc` to do something like `mpc search album $ALBUM_NAME`, but as far as I can tell, both DB entries correspond to only one file on disk. Wiping the DB and re-updating is the only way I have found to resolve this.

The music dir is on an SMB share. I don't know to what extent this is a contributing factor.

**Comment by MaxKellermann** [comment]
> make some modifications to the files and update to add it again

What exactly does "add it again" mean? It's already in the database. "update" updates the existing database entry, it will not create a new one.

> Then the album appears in the DB twice

This doesn't make sense. If you modify a file and update the database, the file will not be there twice.

If you believe this is a MPD bug, write a proper bug report. But since you decided to delete the whole bug reporting template, there isn't even anything we can discuss right now.

**Comment by valrus** [comment]
In case anyone comes across this thread with a similar problem, a followup: the strange behavior I found and described poorly was not an MPD bug. It was because the share that my music was on used a case-sensitive file system, whereas the machine running MPD (macOS) is case insensitive. If files got added to mpd's database and then moved to another path that differed only in case and added again, so that the MPD database had e.g. both

```
Future of the Left/Travels With Myself And Another/01 Arming Eritrea.mp3
Future Of The Left/Travels With Myself And Another/01 Arming Eritrea.mp3
```

then updating would not remove either of them, because (as I understand it) from the perspective of the case-insensitive client both of those files exist. The solution was to move the files to a location outside the MPD music directory, do an `mpd update` to remove them, and then re-add them at the intended path and `mpd update` again to re-add them.
