### ISSUE TITLE
database not updated

### ISSUE THREAD

**Issue by RomainOry** [MusicPlayerDaemon/MPD#1783]
https://github.com/MusicPlayerDaemon/MPD/blob/8f41e05a39959a60e88b70357fab287b22e460e2/src/db/update/InotifyQueue.cxx#L76

When an inotify event occurs in root music folder, uri_utf8 is empty and path_in(uri_utf8, current_uri) return true. The event is not queued and no update is triggered.

**Comment by MaxKellermann** [comment]
Incomplete bug report. You deleted the whole bug reporting template and refused to provide any information. You make it impossible for me to reproduce your problem.
I suspect you never saw this bug occur, but only figured from the code that this could theoretically happen. But the code you described is only reachable if an update is already queued (or else no `current_uri` exists). In that case, no update needs to be triggered because it has already been triggered. Maybe there is a bug somewhere, but your description fails to describe it properly.
