### ISSUE TITLE
Favorites (Loved) tracks

### ISSUE THREAD

**Issue by Solarunit** [MusicPlayerDaemon/MPD#1844]
## Feature request

It would be nice to have an ability to mark (or tag) songs by "favorite" or "loved" symbol or tag. 
Something like this:

![tauon](https://github.com/MusicPlayerDaemon/MPD/assets/20891064/6c00ea56-4c56-4579-9709-9fcc6c94fc4c)

**Comment by MaxKellermann** [comment]
That is possible, has been for 14 years already, since stickers were added. The interpretation of stickers, however, is up to clients. As you already saw in that other thread: if you want UI changes, the UI must be changed, but MPD is not the UI, but the backend. The backend has all the features and is flexible to do everything you want to do.

**Comment by Solarunit** [comment]
I didn't know about stickers. Gonna check them out, thanks.
