### ISSUE TITLE
In the middle of a song, prev should restart the current track rather than play the previous track

### ISSUE THREAD

**Issue by noahrama** [MusicPlayerDaemon/MPD#1918]
## Feature request
If a track is more than 5 seconds in, `mpc prev` ought to restart the track rather than play the preceeding one. 

This behaviour is simillar to what one might expect from a cd player. 

Disabled by default, this option could be added to the mpd configuration

**Comment by GK-774** [comment]
Then "previous" would not mean "previous" any more, bad idea.

**Comment by MaxKellermann** [comment]
A long time ago, MPD used to work that way, but that was changed 15 years ago in commit a5960c20cc679132e049fc6da0f3d7d6fa34e361 because somebody rightfully complained that this behavior would contradict with the meaning of "previous".

Clients which desire to restart the current song can simply send `seekcur 0`. I'm not convinced that we need a global option to change the `previous` command behavior.

**Comment by noahrama** [comment]
> Then "previous" would not mean "previous" any more, bad idea.

Nothwithstanding that i don't believe anybody would be confused such behaviour, it's a strange argument to make, considering that the "previous" functionality mpd differs from the functionality of the following services:

1. Youtube
2. Youtube Music
3. Apple Music
4. Soundcloud
5. Newpipe

I tested them all. Infact i cant find anything which replicates mpd's behaviour. So it seems there is substantial evidence against your reasoning that "previous" means "previous". 

> Clients which desire to restart the current song can simply send `seekcur 0`. I'm not convinced that we need a global option to change the `previous` command behavior.

That would interfere with my keybindings. 

Look, i don't know why in 2009 @MaxKellermann decided to acquiesce to a preferential request from a user. I can't explain given the duration of time since then, why such behaviour hasn't been rectified.

If in 2009 you thought 'cd emulation' was passe, in 2024: i don't think it is.

**Comment by MaxKellermann** [comment]
This feature request is pointless because what you want is already possible without any change to MPD.

You have a different opinion on what the "previous" should mean, but your "evidence" is just cherry-picked examples from people who share your opinion and built them into their software. Your opinion is fine, but so is mine.

But again, since implementing your opinion is possible without any change to MPD, let's just keep our different opinions and everybody uses MPD the way they want to.
