### ISSUE TITLE
Sample rate latency setting

### ISSUE THREAD

**Issue by rferguson10** [MusicPlayerDaemon/MPD#295]
Some DACs have an internal relay to mute while switching sample rates. In my case it's the schiit bifrost but I've heard it happens with others as well. It lasts about 1 or 2 seconds, thus cutting of the first bit of the song.

Was wondering if there's a workaround or a feature that could be added to detect this change, and wait a specified amount of time.

**Comment by MaxKellermann** [comment]
You can ask MPD to use one fixed sample rate for everything, which avoids switching the sample rate. MPD will then resample everything with a different sample rate.

**Comment by rferguson10** [comment]
The downside with that is you aren't getting the most out of say, a 96kHz track if switching from 44.1. I've also tried turning the buffering up, but that only seems to work when jumping around in a track, and not starting one from the beginning.

**Comment by MaxKellermann** [comment]
The decoder buffer is already full with data from the next track when the current track finishes. That's why those settings don't affect your problem. Don't mess with buffer settings, anyway.
What you can do is add a delay to the MPD source code and recompile, but that's not a good general solution.
The general solution is to not use DACs with this "internal delay".
