### ISSUE TITLE
Volume issue with min and max value (using ALSA softvol plugin)

### ISSUE THREAD

**Issue by joerg-krause** [MusicPlayerDaemon/MPD#362]
Commit 967af603270246f1c97e11b8bad6a0eb65c81318 introduced an issue setting the relative volume. The issue happens on my system using the ALSA softvol plugin. The volume range of the softvol plugin is 0..255.

If current Master volume is 251 `mpc volume +5` does not set the volume to max (=255) anymore.
If current Master volume is 7 `mpc volume -5` does not set the volume to min (=0) anymore.

I've added a debug message in [AlsaMixerPlugin](https://github.com/MusicPlayerDaemon/MPD/blob/608d232373f87f230a32838cecfcca63b8e709f7/src/mixer/plugins/AlsaMixerPlugin.cxx#L287):

```c
        fprintf(stderr, "SetVolume: vol: %f\n", cur + 0.01*delta);
	int err = set_normalized_playback_volume(elem, cur + 0.01*delta, delta);
```

.. and one in [volume_mapping](https://github.com/MusicPlayerDaemon/MPD/blob/608d232373f87f230a32838cecfcca63b8e709f7/src/mixer/plugins/volume_mapping.c#L138):

```c
		value = lrint_dir(volume * (max - min), dir) + min;
                fprintf(stderr, "set_normalized_volume: set_raw: %ld %ld %ld\n", min, max, value);
```

These is the debug output when running `mpc volume +5` if current volume is 251:
```
SetVolume: vol: 1.004314
set_normalized_volume: set_raw: 0 255 257
```

These is the debug output when running `mpc volume -5` if current volume is 7:
```
SetVolume: vol: -0.002549
set_normalized_volume: set_raw: 0 255 -1
```

My first thought would be to check the limit value in `SetVolume` for `0 ≤ (cur + 0.01*delta) ≤ 1`. What do you think of that?

**Comment by miccoli** [comment]
In fact [`set_normalized_volume`](https://github.com/MusicPlayerDaemon/MPD/blob/bd115a40081ec6527e1e13231caec23f36768d73/src/mixer/plugins/volume_mapping.c#L123) seems problematic...

I would fix this with miccoli@6d48a5684a2a05176b5dc0107e557edffb7d0673 (I had no time to check this right now, but I will do it shortly and open a PR if all works as expected.)

A brief note: after 967af60 [`AlsaMixer::SetVolume`](https://github.com/MusicPlayerDaemon/MPD/blob/793fd8c47996db74c7d10a2e101cd44311d7c06e/src/mixer/plugins/AlsaMixerPlugin.cxx#L281-L291) is overshooting by design, to avoid the lock problems described in #104, so it is expected that occasionally `(cur + 0.01*delta)` is `<0` or `>1` but it was assumed that `set_normalized_volume` would clamp the volume to valid values. Maybe a better solution is possible in `AlsaMixer::SetVolume`, but for now I would fix `set_normalized_volume`.
