### ISSUE TITLE
search / playlistsearch partial search not supported with filter expressions

### ISSUE THREAD

**Issue by cotko** [MusicPlayerDaemon/MPD#410]
Old commands for searching DB / playlist also work for partial searches:
```
// return all songs with artist containing word 'empire'
search "artist" "empire" 
playlistsearch "artist" "empire"
```
Now with filter expressions, this feature does not work any more, it seems it stopped working somewhere around the [bugfix to support escaping of `'` and `"`](https://github.com/MusicPlayerDaemon/MPD/commit/528f5b9cb94821e9b5e575b8ce99440bbbfc38ad):
```
// did return partial matches (somewhere) before the above commit and now they do not any more
search "(artist == 'empire')"
playlistsearch "(artist == 'empire')"
```

If this is intended, then we need an alternative, if old `TAG VALUE` are being "deprecated" in favour of `filters`. Maybe `=~` like for *AudioFormat* matching. But then there is another question - will there still be a need for separate *find* and *search* at all?:)

**Comment by MaxKellermann** [comment]
The documented difference between `find` and `search` is that `search` is case insensitive. There never was a mention in the protocol documentation about `search` matching substrings. That has always been a bug (implementation or documentation bug - no idea).

**Comment by geneticdrift** [comment]
In the case of `search` matching substrings, I think it's better to call it an _undocumented feature_ than to call it a bug and then change the behavior. It is useful as @cotko explained and clients have already been using it as it is for a long time.
If at all possible, please don't break existing client.

**Comment by MaxKellermann** [comment]
Agree, @geneticdrift. This will not be changed in the legacy syntax. However, the new syntax will not match substrings with operator `==` because this would be a surprising feature. There will be a new operator for matching substrings. (It will not be `=~` because that one will be another new operator for matching a regular expression, same as in Perl.)

**Comment by cotko** [comment]
Yey! :+1: :)

**Comment by geneticdrift** [comment]
Regarding Perl-compatible regular expression:
The documentation reads: `This feature is only available if MPD was compiled with libpcre`

Will the client be able to check the availability of this through the protocol?

Currently a client can use `commands`, `not commands` and `tagtypes` to match supported features, but it also has to test the protocol version because some command modifiers/filters are being added/changed in MPD releases.
Now there's also a build dependent feature that is not protocol version dependent.
One other example is the stored playlists that's currently not supported in the android build.

So may be it will be beneficial to add a `features` command for the client to query and configure itself accordingly.
Testing for the error code from a command would work too but would complicate the client and possibly be less end-user friendly (better to show disabled function upfront than to show an error after the fact).
