### ISSUE TITLE
Android: mpd complains about file permissions when running with custom mpd.conf

### ISSUE THREAD

**Issue by roizcorp** [MusicPlayerDaemon/MPD#417]
When running vanilla (no mpd.conf) everything works correctly

When applying custom mpd.conf it complains it does not have permission to mpd's files such as state file

**Comment by MaxKellermann** [comment]
So which paths did you configure? Paste your log.

**Comment by gdub010101** [comment]
@roizcorp I had to grant MPD Storage permission under App settings in order to stop permission errors about accessing my mpd.conf file.  I don't recall errors about the state file.  However, perhaps you just need to give MPD Storage permission if you haven't.  Something like Settings > Apps > MPD > Permissions > Storage, toggle it on.  See if that helps.

**Comment by roizcorp** [comment]
Sorry, I should have mentioned it, I have granted the storage permission already.

I'm not sure how to export the mpd.log from android 
Now that you mentioned it, I have not configured any paths - I just configured the db to be as a proxy plugin and assumed that any path that I did not configure MPD will go to default.

So it did try to use the default `/data/user/0/org.musicpd...` then it complains about the permissions

**Comment by roizcorp** [comment]
will do! (just need to return home first :) )

**Comment by roizcorp** [comment]
I changed the infrastructure in my IT - now it seems to work - I have no idea how to make it complain again
closing issue
