### ISSUE TITLE
Add support for embedded cover art

### ISSUE THREAD

**Issue by Holzhaus** [MusicPlayerDaemon/MPD#42]
Support for embedded covert art is currently missing. Most MPD clients fall back to downloading album covers from web services like amazon. Unfortunately, this can result in wrong or no covers being displayed, especially when listening to uncommon or older releases.

Since it's possible embed cover art in music files using [Vorbis comments](https://wiki.xiph.org/VorbisComment#Cover_art) and [ID3v2 tags](https://wiki.xiph.org/VorbisComment#Cover_art), ), MPD should be able to read and transmit the embedded image data to the client (possibly as a `base64`-encoded string).

**Comment by coderkun** [comment]
Some clients also use a configurable (base) URL to download the cover files from (e. g. cover.jpg) served by a webserver that is set up next to MPD itself.

**Comment by raftopoulos** [comment]
IMHO MPD should not transfer data. Better use CIFS, NFS, FTP, HTTP et cetera.

Provide a consistent mechanism for clients to locate files with embedded graphics or default to generic image file.

1. MPD scans file for embedded cover art. If successfull write hint to database.
2. MPD (mpd.conf plus filename) knows URI of file. For example http://my.mpd.server/muzak/file-with-coverart.mp3
3. Client asks server for URI and retrieves file.
4. No embedded cover art? Fallback URI to (cover|folder).(gif|png|jpeg) file in same directory

**Comment by coderkun** [comment]
@raftopoulos, sounds good to me. I agree that MPD should not serve these files itself but a consistent way of handling cover files would be a great improvement.

**Comment by Holzhaus** [comment]
@raftopoulos If I understand you correctly, your proposal would imply that the user has to set up his or her own HTTP server. What about authentication? If I password-protect my MPD server, will I have to keep the the passwords of MPD and the HTTP server in sync manually?

I'd propose that we introduce a new MPD-only tag that acts as an Image ID. This ID is generated by the MPD server and is a hash value based on image data (e.g. a SHA512 hash or something like that). That hash value will be used like any other tag and saved in MPDs database.

If a client  wants to display an album cover of a song, it will first look up that image ID inside it's own client-local cache directory (which contains files named `<imageID>.jpg`) and use that image if it's already present. If not, that image could be fetched directly via a new `readimage` command that return the `base64` encoded image data. This would take care of superfluous file transfers: Identical images have the same hash value and thus the client does not re-request the image transfer. Also, it's easier to set up and does not interfere with the MPD password-protection mechanism.

Support for treating per-folder image files (e.g. `folder.jpg`) as album art could be added, but since not everyone uses separate folders for their music library, this should only act as a fallback solution or be configurable (preferably by being able to configure a comma-separated list of filenames or evan a RegEx).

**Comment by raftopoulos** [comment]
Proposed URI is not tied to HTTP - eg nfs://my.mpd.server/muzak/file-with-coverart.mp3 or smb://mpd/muzak/file-with-coverart.mp3

Add data transfer functionality to MPD... you have to convince Max, not me.

Fallback to folder.jpg: ACK. No CSV only Regex - we are grown-ups ;)

**Comment by ArchangeGabriel** [comment]
HTTP, NFS, CIFS, FTP, whatever: this require a supplemental access than what is currently to run MPD. My MPD server file system is not exposed over anything, yet I’d like for MPD to provide cover art to clients. So I like @Holzhaus proposal. ;)

**Comment by rhoering** [comment]
@AG: love your Guthrie nickname

@all: I saw an active thread flash through my inbox for MPD dev on the cover art.  Take a look at the MPD dev requests.

**Comment by rhoering** [comment]
@ag: iPhone autocorrect. 'github' not 'Guthrie'

**Comment by Holzhaus** [comment]
Can't find anything recent concerning cover art on [mpd-devel](http://mailman.blarg.de/pipermail/mpd-devel/). Am I looking in the wrong place?

**Comment by tokyovigilante** [comment]
Hi, I'm interested in this feature as well, as I'm writing an MPD client with the intent of controlling both a local MPD instance and an instance on my NAS. 

I'm currently using a last.fm lockup with local caching, but don't want to have multiple copies of the art distributed round my devices, and would prefer to use a copy stored with my music. I can see three ways forward:

1. MPD could advertise the direct or SMB/NFS path to the art with other metadata. This puts the burden of retrieval on the client, but this is acceptable for most cases. Downside may be security, and I note that lookup of MPD's music directory using the config command is limited to local clients.

2. MPD could parse out embedded album artwork from metadata. I don't really like this approach because as others have noted, it's per-album info not per-track info and this leads to unnecessary duplication, particularly if using high-res artwork. 

3. MPD could run it's own HTTP server to provide the art. Not ideal given this would require more configuration, overhead of server code or a separate instance.

3. MPD could provide the image data directly over the TCP client connections. I personally don't think this is a bad option but seems to be frowned upon by some of the developers?

I'm currently hacking away on the MPD source to try these options. I'd appreciate any feedback from the developers which would be the best/preferred option, or at least which is most likely to have a pull request accepted :)

**Comment by MaxKellermann** [comment]
@tokyovigilante each of these options has a downside; (4) would be interesting because it would "just work", however it requires a major protocol extension for binary transfer. That is something I've been shying away from for very long, because it's hard to do well, and it makes the protocol non-trivial.
The advantage of (3) would be that the client could delegate the transfer to another entity (web browser?), but it adds difficulties with routing and firewalling, because it requires another open port and another connection. Since I want everything to "just work", it may not be the best option. But it uses an existing protocol, and no major protocol extension for MPD.
(1) is trivial to do, but makes the disadvantage of (3) even larger: it requires the clients to have valid credentials for that SMB/NFS server, they need to be able to connect to it, and they must have client support for these protocols. Won't work, too complicated for users.
(2) isn't just another option; it's a feature orthogonal to the other choices. Yes, MPD should support that.
I'd go for your (4).

**Comment by mray** [comment]
@ (2)
Couldn't the server offer a hash of the embedded file and make sure the client only asks for it once?
I like the idea of getting embedded images *directly*.

**Comment by tokyovigilante** [comment]
@MaxKellermann thanks for your reply. I like the idea of transferring the file over the wire best as well. Over gigabit even if it's 1MB in size it should only take a fraction of a second. In terms of API, thoughts are to have two (possibly three) new functions (best not to modify existing API). 

First - "getalbumartsize [song URI]" taking a URI in the database as a parameter (searching by album and artist could also work, but this is working on the assumption that the art is in the same folder as the file we're interested in getting art for). This can return -1 if the art doesn't exist, and the file size in bytes if it does.

Second "getalbumart [song URI]" will actually return the art as raw data over the wire. Since the client knows the size in advance this will optimise the TCP transfer, and I'd envisage using a second socket connection for this in most cases (assuming this makes sense given MPD's thread module? How long can the server block writing to a socket before playback is affected?). The client can obviously cache this image for that combination of album and artist locally for the session.

Possible third could be "getalbumartformat [song URI]" to return the image type, but for my purposes at least (using Cocoa/Swift on OS X) NSImage (and UIImage on iOS) is capable of opening any supported image type (png, jpg, tiff etc) based on the file header data without an extension. If other clients need to know type or only support a subset of image types this third command should be easy enough to add.

Thoughts? I'd appreciate some help on the best mpd APIs to use as I have a C/Objective-C (now Swift) rather than C++ background, but will try and add the commands and work with the file system APIs a bit first.

@mray I'm not sure what you mean regarding the hash? You'd still need a mechanism to actually transfer the image from server to client which is the tradeoff I think here.

**Comment by MaxKellermann** [comment]
> How long can the server block writing to a socket before playback is affected?

The main thread is not involved in playback; it only selects the "next" song and sends commands. But that's the wrong question. It is completely not acceptable to block the thread, no matter how quickly you can do it in the best case; the worst case is what counts for the design. All I/O must be non-blocking, which is why the `Client` class has an output buffer for responses, and this buffer is submitted to the socket in a non-blocking manner.

I don't think it's a good idea to develop a protocol that requires the client to maintain a second connection to MPD only for data transfers. (Badly designed clients will always do that, but it must be possible for good clients to use one single connection. I want to help the good developers.)

Your argument "1 MB on Gigabit takes only one second" does not convince me. It must be possible to run a MPD client across slow mobile networks as well, not just your fast LAN. If the protocol makes the connection unusable for a minute just because you're downloading that multi-megabyte file over a bad GSM network, it's a bad protocol.

And finally, I don't like your idea of splitting this into two or three commands (for album art; for each additional file type another 3 commands). For the protocol, it is not necessary to know the size in advance; the first response line could indicate metadata like file size, and then the transfer could begin.

One possible approach for the "slow network" problem could be to do the transfer in smaller chunks (a few kB, small enough to fit in `Client`'s output buffer), and after one chunk, the client can request more data, or decide to do something else, like update the status, and then continue the transfer.

This is how I imagine it:

    albumart foo/bar.mp3 16384
    OK MPD 0.21.0
    size: 65536
    offset: 16384
    type: image/jpeg
    binary: 8192
    [followed by 8192 bytes of binary data]

The client requests albumart data (I'd rename this command to something more generic, I just use your suggestion for the demonstration), starting at offset 16384. MPD replies with some metadata about the file, and then begins a binary transfer with the "binary" line, which indicates how many binary bytes will be available (starting after the newline character).

**Comment by mray** [comment]
@tokyovigilante I was just addressing the unnecessary multiple copies of the art distributed. You could cache album covers and not transfer each songs embedded image if you already have it.

**Comment by tokyovigilante** [comment]
> All I/O must be non-blocking, which is why the Client class has an output buffer for responses, and this buffer is submitted to the socket in a non-blocking manner.

That's fair, I thought it might be reasonable to rely on the underlying kernel TCP buffer, but obviously this can't be set by mpd.

> I don't think it's a good idea to develop a protocol that requires the client to maintain a second connection to MPD only for data transfers. (Badly designed clients will always do that, but it must be possible for good clients to use one single connection. I want to help the good developers.)

This is absolutely a side point, but I can't see how to use the idle command in that instance? I have my client set up to establish an idle connection then watch for updates to avoid polling for status changes, but then use a second socket as and when required to send playback commands, get updates etc.

>  It must be possible to run a MPD client across slow mobile networks as well, not just your fast LAN.

Again good point, I'd imagined a client for mobile might choose not to request the art in this instance, but you're right, its not a good fit for slow/unreliable networks.

> And finally, I don't like your idea of splitting this into two or three commands (for album art; for each additional file type another 3 commands). For the protocol, it is not necessary to know the size in advance; the first response line could indicate metadata like file size, and then the transfer could begin.

This is a much better approach, thanks.

> One possible approach for the "slow network" problem could be to do the transfer in smaller chunks (a few kB, small enough to fit in Client's output buffer), and after one chunk, the client can request more data, or decide to do something else, like update the status, and then continue the transfer.

Make sense, I like your proposed structure for the response.

The client requests albumart data (I'd rename this command to something more generic

> Sure, but what other use cases do you have in mind? Clearly a binary transfer protocol is useful, but I can't think of anything else to transfer other than album art, unless you were thinking about PCM or compressed audio data? That might be quite a big change to what the server's responsibilities are though.

@mray Right that makes sense. I've just been chucking them in a cache folder with artist/album/art.jpg structure. I think the real issue is where the art is coming from, for example for offline players/clients. Also for browsing big libraries storing that art locally starts to get sizeable, and I assume most people would be running mpd on a server with bulk storage attached either locally or over network share.

**Comment by MaxKellermann** [comment]
> I can't see how to use the idle command in that instance? I have my client set up to establish an idle connection then watch for updates to avoid polling for status changes, but then use a second socket as and when required to send playback commands, get updates etc.

No, no, no, that's the wrong way to use `idle`! Your one single connection should always be in `idle` mode. Now the user presses "pause" or something, then your client sends `noidle`, followed by `pause`, and then re-enters `idle`. Why would you need a second connection?

**Comment by tokyovigilante** [comment]
> Why would you need a second connection?
I guess I'm mainly thinking of the (contrived) screnario where two clients are connected, and one causes a change in a subsystem while the other is between noidle and idle (ie updating its own status or sending a command). Does mpd cache those update messages on that case?

**Comment by MaxKellermann** [comment]
If something happens while the connection is busy, the next `idle` will return immediately, reporting those events. `idle` will never miss an event.

**Comment by tokyovigilante** [comment]
> If something happens while the connection is busy, the next idle will return immediately, reporting those events. idle will never miss an event.

Outstanding, I hadn't appreciated that. Using a single socket makes perfect sense now. 

OK I'll see what I can come up with over the next few days. Thanks!

**Comment by tokyovigilante** [comment]
First attempt at #86 with comments.

**Comment by hal-ullr** [comment]
I think reading embedded cover art is preferable for a few reasons.

1. Digital albums (compilations and others) that use per‐track album art do not serve the incorrect art
2. The space‐saving measure of having per‐directory album art is negated in any case where the user uses any other software that requires embedded cover art, in which case this behavior actually requires additional space.
3. There is no prescribed directory format.

**Comment by ochurlaud** [comment]
Two questions:
1) Why isn't this issue closed since #86 was merged?
2) When is this expected to be released?

This feature is awesome. But it will take time to reach all clients I'm afraid

**Comment by thenktor** [comment]
Hi, is there already some documentation about this?

**Comment by MaxKellermann** [comment]
> Hi, is there already some documentation about this?

Look at the commit which closed this issue.

**Comment by thenktor** [comment]
OK, so now there is the `readpicture` command? Somewhere else I've read about the `albumart` command, that looked quite the same?
Which album arts are returned? Only in tag embedded ones or also cover.jpg inside the same folder as the music files?

**Comment by MaxKellermann** [comment]
> Which album arts are returned? Only in tag embedded ones or also cover.jpg inside the same folder as the music files?

This is documented. Do you have difficulties understanding the documentation?

**Comment by thenktor** [comment]
> This is documented. Do you have difficulties understanding the documentation?

Next time just say, that the documentation can be found here: https://www.musicpd.org/doc/html/protocol.html?highlight=cover

That actually also would have been the answer to my first question,

**Comment by MaxKellermann** [comment]
If you believe the MPD documentation is too hard to find, submit a PR to https://github.com/MusicPlayerDaemon/website/
I cannot imagine how to make it easier to find - easier than having a "Documentation" link in the navigation bar on each page of the MPD website. (And a full copy of the documentation is part of the MPD source tarball.)

**Comment by thenktor** [comment]
I could find the documentation, but not the page with the relevant information.

**Comment by pozemka** [comment]
It seems this ticket is about **embedded** cover art which is still not implemented. So why it was closed?
I see that current implementation is only searches cover images in music directory. Or I am missing something and embedded art is supported too?

**Comment by MaxKellermann** [comment]
You are missing something, @pozemka.

**Comment by fn-ix** [comment]
> You are missing something, @pozemka.

Can you elaborate, please?

**Comment by MaxKellermann** [comment]
> Can you elaborate, please?

Again? Ok ...
That was in reply to

> Or I am missing something and embedded art is supported too?

Embedded cover art is supported, which was the whole point of this PR. The feature was discussed here, and the documentation was discussed and linked here. Therefore, the possibility that remains is that pozemka was "missing something" (just as they said).

**Comment by fn-ix** [comment]
Yes yes, my bad, turns out it's a client side issue for me.
