### ISSUE TITLE
'tidal' And 'Qobuz' are unavailable

### ISSUE THREAD

**Issue by LinArcX** [MusicPlayerDaemon/MPD#430]
Hi. i want to use ncmpcpp alongside mdp. follow instructions in:
https://wiki.archlinux.org/index.php/Music_Player_Daemon
https://wiki.archlinux.org/index.php/Ncmpcpp
everything seems fine, but when i try to update list of musics in ncmpcpp, these logs appear:

```
» mpd --stdout --no-daemon --verbose
config_file: loading file /home/linarcx/.config/mpd/mpd.conf
libsamplerate: libsamplerate converter 'Fastest Sinc Interpolator'
vorbis: Xiph.Org libVorbis 1.3.6
opus: libopus 1.3
sndfile: libsndfile-1.0.28
hybrid_dsd: The Hybrid DSD decoder is disabled because it was not explicitly enabled                                                 
wildmidi: configuration file does not exist: /etc/timidity/timidity.cfg                                                              
simple_db: reading DB
output: No 'audio_output' defined in config file
output: Attempt to detect audio output device
output: Attempting to detect a alsa audio device
output: Successfully detected a alsa audio device
exception: Input plugin 'tidal' is unavailable: No Tidal application token configured                                                
exception: Input plugin 'qobuz' is unavailable: No Qobuz app_id configured                                                           
curl: version 7.62.0
curl: with OpenSSL/1.1.1
avahi: Initializing interface
exception: RTIOThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted       
avahi: Client changed to state 101
avahi: Client is CONNECTING
inotify: initializing inotify
inotify: watching music directory
client: [0] opened from [::1]:57724
client: [0] process command "status"
exception: Failed to read mixer for 'My ALSA Device': no such mixer control: PCM
client: [0] command returned 0
client: [0] process command "plchanges "0""
client: [0] command returned 0
client: [0] process command "outputs"
client: [0] command returned 0
client: [0] process command "decoders"
client: [0] command returned 0
client: [0] process command "outputs"
client: [0] command returned 0
client: [0] process command "outputs"
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
client: [0] process command "update "/""
update: spawned thread for update job id 1
client: [0] command returned 0
update: starting
client: [0] process command "idle"
client: [0] command returned 1
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
update: finished
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
```

**Comment by MaxKellermann** [comment]
What kind of assistance do you seek here? Do you believe this is a bug?

**Comment by LinArcX** [comment]
I don't know this is a bug or not. You maybe help me what's going on.

**Comment by MaxKellermann** [comment]
You did not configure a Tidal application token. And you did not configure a Qobuz app_id. Therefore, these two plugins are not available.
Is that a problem for you? Or why did you report this condition?

**Comment by MaxKellermann** [comment]
Will reopen when you explain what this is about.

**Comment by fschlich** [comment]
When starting mpd without --verbose and configured to log to a file, the three lines about Tidal, Qobuz and hybrid_dsd are still printed to stderr, making them stand out as if there's something seriously wrong.

One way to deal with this could be to lower the severity of these messages, so they only get logged and are invisible on stdout. Another way could be to add sections to the default config that disable these plugins and inform the user about necessary tokens or app_ids, perhaps like so:

```
# QOBUZ input plugin
input {
        enabled    "no"
        plugin     "qobuz"
#        app_id     "ID"
#        app_secret "SECRET"
#        username   "USERNAME"
#        password   "PASSWORD"
#        format_id  "N"
}

# TIDAL input plugin
input {
        enabled      "no"
        plugin       "tidal"
#        token        "TOKEN"
#        username     "USERNAME"
#        password     "PASSWORD"
#        audioquality "Q"
}

# Decoder #####################################################################
#

decoder {
        plugin                  "hybrid_dsd"
        enabled                 "no"
#       gapless                 "no"
}

```

**Comment by Pablo1107** [comment]
I agree with @fschlich , this messages appears as exceptions, givin the impression there something wrong in you system or your config file. It should't appear on stderr.

**Comment by Kipparis** [comment]
and where is the answer? :/

**Comment by MaxKellermann** [comment]
> and where is the answer? :/

Answer to what? There are 4 questions in this thread, and I asked all of them, but nobody replied.

**Comment by robertbeal** [comment]
I've just come across this as part of solving an issue with my MPD instance. I'm using a freshly installed debian and mpd (v 0.21.5). I've not configured either plugin yet on stderr I get the below which was very misleading in trying to figure out what was wrong.

I agree with the above, we shouldn't be seeing such output when we haven't used or configured those plugins.

```
Feb 08 21:34 : exception: Input plugin 'tidal' is unavailable: No Tidal application token configured
Feb 08 21:34 : exception: Input plugin 'qobuz' is unavailable: No Qobuz app_id configured

**Comment by charlie39** [comment]
I am getting this in 2020.
There's a new plugin new decoder plugin to the list, wildmidi.
Followed what  @fschlich mentioned. Looks like a temporary patch

**Comment by je-vv** [comment]
Though it seems mpd seems to work just fine, the 3 exceptions just show up on stderr, but not the log (without a hint they are from mpd, which is kind of hard to guess with services starting in parallel).  Now I know, whenever starting mpd I get on the stderr:
 
> Mar 22 23:57 : exception: Decoder plugin 'wildmidi' is unavailable: configuration file does not exist: /etc/timidity/timidity.cfg
> Mar 22 23:57 : exception: Input plugin 'tidal' is unavailable: No Tidal application token configured
> Mar 22 23:57 : exception: Input plugin 'qobuz' is unavailable: No Qobuz app_id configured

Having those misleading exceptions showing up as errors, and with no source indication, makes people looking around for what's failing, when there's really nothing failing.  Adding fake plugins and decoders by configuration is not good, as the amount of plugins might increase (now there are 3 exceptions as opposed to 2 as before).

So perhaps the MPD devs can consider preventing throwing those exceptions as errors, and perhaps include them at most as warnings in the log.  That would be really helpful.  Thanks a lot !

**Comment by MaxKellermann** [comment]
> So perhaps the MPD devs can consider preventing throwing those exceptions as errors, and perhaps include them at most as warnings in the log. That would be really helpful. Thanks a lot !

You mean, for example, something like https://github.com/MusicPlayerDaemon/MPD/commit/40a48cfba0a ?

**Comment by je-vv** [comment]
Yes !  Thanks a lot !

**Comment by himanshuxd** [comment]
Like many have pointed out these three are optional stuff and shouldn't appear on stderr, also add these lines to `~/.config/mpd/mpd.conf` to whoosh them away :

`input {
        enabled    "no"
        plugin     "qobuz"
}

input {
        enabled      "no"
        plugin       "tidal"
}

decoder {
       enabled                  "no"
       plugin                   "wildmidi"
       config_file              "/etc/timidity/timidity.cfg"
}`

**Comment by BachoSeven** [comment]
> Like many have pointed out these three are optional stuff and shouldn't appear on stderr, also add these lines to `~/.config/mpd/mpd.conf` to whoosh them away :
> 
> ```
> input {
>         enabled    "no"
>         plugin     "qobuz"
> }
> 
> input {
>         enabled      "no"
>         plugin       "tidal"
> }
> 
> decoder {
>        enabled                  "no"
>        plugin                   "wildmidi"
>        config_file              "/etc/timidity/timidity.cfg"
> }
> ```

Thanks, I agree that it is not, in my opinion, the preferred behaviour to print those warnings to stderr as they fill my xorg warnings, thus your workaround is appreciated

**Comment by m040601** [comment]
> Like many have pointed out these three are optional stuff and shouldn't appear on stderr, also add these lines to ~/.config/mpd/mpd.conf to whoosh them away :+1: 


```
input {
        enabled    "no"
        plugin     "qobuz"
}

input {
        enabled      "no"
        plugin       "tidal"
}

decoder {
       enabled                  "no"
       plugin                   "wildmidi"
}
```


Thank you to @himanshuxd all the users who helped other users with these 9 simple lines of code.


> this messages appears as exceptions, giving the impression there's something wrong in you system or your config file

Of course they give that impression. That's for 99.9% of mpd users. Except for those 0.1% unimpressionable. Thats why there are still people ending up here in 2020, for an issue opened in 2018.


> You mean, for example, something like 40a48cf ?

Since those 99.9% are mostly busy with output plugins, and are not going to go dig into the source code,to discover this "obvious simple setting" 
could I ask to include this in the docs ?

Perhaps update the "mpdconf.example" provided ?
I bet making 

Make it prominent in the user manual, and make it crystal clear that you can
turn thing on/off with this "enabled" line.simple syntax, 
```
XYZ {
        enabled      "yes/no"
        plugin       "FOOBAR"
}
```

**Comment by MaxKellermann** [comment]
> Thank you to @himanshuxd all the users who helped other users with these 9 simple lines of code.

Those 9 lines of code are not necessary anymore. At least for those people running the latest MPD version.

Why are we still discussing this? As I wrote 4 months ago, this "problem" is obsolete. It no longer exists.

> Of course they give that impression. That's for 99.9% of mpd users. Except for those 0.1% unimpressionable. Thats why there are still people ending up here in 2020, for an issue opened in 2018.

This issue was opened in 2018, but there was no reply to my questions until 2020. After that, when I understood what this is about, I changed MPD accordingly.

People are still ending up here because they use old MPD versions. You see old problems with old MPD versions, obviously!

> 
> > You mean, for example, something like [40a48cf](https://github.com/MusicPlayerDaemon/MPD/commit/40a48cfba0ab5f654373eb4c82a15851f5c94e3b) ?
> 
> Since those 99.9% are mostly busy with output plugins, and are not going to go dig into the source code,to discover this "obvious simple setting"

Nobody needs to dig into the source code, because:

> could I ask to include this in the docs ?

Already included: https://www.musicpd.org/doc/html/user.html#configuring-input-plugins

"enabled yes|no 	Allows you to disable a input plugin without recompiling. By default, all plugins are enabled."

That's why it's so frustrating to write documentation. Nobody reads it, and yet people demand to add text to it that is already there.

> Make it prominent in the user manual, and make it crystal clear that you can
> turn thing on/off with this "enabled" line.simple syntax,

If you make one thing "prominent", people will not read everything else, and will demand making those other things "prominent". Or they won't even read the prominent things. (Whatever "prominent" means.)

Everybody believes his own current issue is the most important thing and documentation should be more clear about it. Yes, the documentation is pretty bad. You can say lot of things about it, and there's lot of room for improvement. But what you just complain about isn't one of those things.

But if you have an idea how to improve the documentation for everybody, submit a pull request.

**Comment by m040601** [comment]
> People are still ending up here because they use old MPD versions

Arch Linux,

uname -a
`Linux gigabyty 5.7.8-arch1-1 #1 SMP PREEMPT Thu, 09 Jul 2020 16:34:01 +0000 x86_64 GNU/Linux
`

mpd --version | grep 0.2

`Music Player Daemon 0.21.25 (0.21.25)`

**Comment by m040601** [comment]
> Already included: https://www.musicpd.org/doc/html/user.html#configuring-input-plugins

doc/html/**_user_**.html#configuring-**_input_**-plugins

This kind of "generic" instruction, making everyone familiar with the syntax of 
the configuration file should not be tied to a specific manual section or specific plugin, be it "input" plugin or
"output" plugin. 

It applies to both ! It should in the opening lines of the section "the-configuration-file" . The goal is to quickly make the user aware of how this "mpd.conf" works. Generically. Is it a init style conf file ? Is it a Yaml style ? Can I repeat some settings inside a block. How can I source other files from here to tidy up my mpd.conf. How do comments work etc.

Again, by simply doing this by example, in the provided example mpd.conf has the same effect.

Another example of this type of mechanism in action is the "bind_to_address" setting.
Yes, we all know, it's there on the manual, very nicely and pretty:

> It can be used multiple times to bind to more than one address. Example:
> 
> bind_to_address "192.168.1.42"
> bind_to_address "127.0.0.1"



`That's why it's so frustrating to write documentation. Nobody reads it, and yet people demand to add text to it that is already there.
`
I agree with you, can surely emphatize with you after many years in technical support.
And before I forget, thank you for all the effort years you have put into this.

But
`

>   ...  text to it **_that is already there_**

That's exactly the point I'm trying to make with the 99.99 thing.

`
Make it prominent in the user manual, and make it crystal clear that you can
turn thing on/off with this "enabled" line.simple syntax,

If you make one thing "prominent", people will not read everything else, and will demand making those other things "prominent". Or they won't even read the prominent things. (Whatever "prominent" means.)

**Comment by MaxKellermann** [comment]
@m040601 indeed, when I wrote the "fix", I chose the wrong log level, so the message is still there in default configurations. Sorry, I was wrong here. The log level fix is now in v0.21.x.

**Comment by tvhung83** [comment]
> By default, all plugins are enabled.

This is a weird behavior. Shouldn't it be disabled by default when it needs extra configs? The software should work with default configuration, instead of saying something is wrong at the first run **when** users don't want any extra functionalities. I understand that it's OSS and it's decided by whoever owns it, just my 2 cents.

**Comment by MaxKellermann** [comment]
> Shouldn't it be disabled by default when it needs extra configs?

That would imply that adding the extra config would still leave the plugin disabled, which would lead to lots of frustration.

**Comment by gwerbin** [comment]
Having plugins for streaming services enabled by default is somewhat surprising behavior. Wouldn't it make more sense to just advise users to set `enabled = "yes"` when configuring an input plugin?
