### ISSUE TITLE
Problem with IN6_IS_ADDR_V4MAPPED on NetBSD

### ISSUE THREAD

**Issue by 0-wiz-0** [MusicPlayerDaemon/MPD#438]
On NetBSD, the build breaks with:
````
In file included from /usr/include/netinet/in.h:372:0,
                 from ../src/net/IPv4Address.hxx:42,
                 from ../src/event/ServerSocket.cxx:22:
../src/net/IPv6Address.hxx: In member function 'bool IPv6Address::IsV4Mapped() const':
../src/net/IPv6Address.hxx:175:10: error: 'ntohl' was not declared in this scope
   return IN6_IS_ADDR_V4MAPPED(&address.sin6_addr);
          ^
````
This might be a problem that's only on NetBSD, and a fix was committed to NetBSD today (https://mail-index.netbsd.org/source-changes/2018/12/10/msg101328.html) but to support older NetBSD releases, the following patch might be useful:
````
--- src/net/IPv6Address.hxx.orig        2018-11-16 12:27:58.000000000 +0000
+++ src/net/IPv6Address.hxx
@@ -41,6 +41,7 @@
 #include <ws2tcpip.h>
 #else
 #include <netinet/in.h>
+#include <arpa/inet.h>
 #endif
 
 /**
````
I don't know if FreeBSD/OpenBSD are affected.

**Comment by MaxKellermann** [comment]
Since this is clearly a NetBSD bug, this should be fixed by NetBSD (and shipped quickly to their users), not by MPD. I don't want to support old and known-buggy operating systems.

**Comment by ffauberteau** [comment]
I just type "man ntohl" on my Arch Linux box and I can read:
```
SYNOPSIS
        #include <arpa/inet.h>
```
I have the same synopsis on one of my NetBSD box.

I don't really understand why NetBSD would by buggy since it implements what it is documented.
```
CONFORMING TO
        POSIX.1-2001, POSIX.1-2008.

        Some  systems  require  the  inclusion  of  <netinet/in.h>  instead  of
        <arpa/inet.h>.
```
Actually, I think Linux-based systems are part of these "some systems"...

Please, could you import the suggested fix that respect the specifications so that we can stop to maintain a patch that is non-sense.

Thanks!
