### ISSUE TITLE
MPD.log corruption

### ISSUE THREAD

**Issue by lak1151** [MusicPlayerDaemon/MPD#452]
MPD.log corrupts with NULLs occasionally.This is running on Rasbian Ver 9 (stretch).Seems related to a ZeroConf logging line. This event is very inconsistant
[mpd.log](https://github.com/MusicPlayerDaemon/MPD/files/2737759/mpd.log)

**Comment by MaxKellermann** [comment]
Since you havn't specified your version number (or ANYTHING else), I must assume that you're using the MPD version which was shipped with Raspbian, and that one is old and unsupported. Please ask the Raspbian project for help with old MPD versions they are shipping, or ask them to ship a new and supported version.

**Comment by lak1151** [comment]
Thanks. Will do.
