### ISSUE TITLE
MPD null pointer dereference crash on LineageOS on OnePlus 5T

### ISSUE THREAD

**Issue by avuton** [MusicPlayerDaemon/MPD#521]
MPD-0.21.6 crashes (repeatedly) as soon as the 'run' button is pressed, or the 'boot' option is enabled. The tombstone has all the technical information that might be interesting, more than I could give alone. As usual, I'm happy to test or give more information.

[The F-Droid build metadata](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/org.musicpd.yml)

[The Android Tombstone](https://github.com/MusicPlayerDaemon/MPD/files/3036360/tombstone.txt)

[The app directory after installation](https://github.com/MusicPlayerDaemon/MPD/files/3036363/org.musicpd-z5jd7LZ5F6sNFOIViFNWGw.zip)

**Comment by avuton** [comment]
Added an [F-Droid](https://gitlab.com/fdroid/fdroiddata/issues/1583) bug in case it's a issue with the metadata.

**Comment by MaxKellermann** [comment]
The crash occurs in the C++ standard library. It is a null pointer dereference, and it doesn't look like this null pointer came from MPD code. But that is hard to tell reliably, because the stack trace in your tombstone is too short. Even if it were longer, the binary is stripped.

I'm sorry I can't help with the information given; if we had a longer stacktrace and an unstripped binary, maybe I could help.

**Comment by ildar** [comment]
@MaxKellermann can you confirm mpd works for you (on Android) ? I experience crashes too.

**Comment by MaxKellermann** [comment]
It works for me.

**Comment by stephengeorgewest** [comment]
Crashes for me as well right after run on Moto g4 play.

**Comment by Thrilleratplay** [comment]
@stephengeorgewest  @ildar  Are you both using LineageOS 14 and installed from Fdroid?  I am also experiencing crashing but the logs don't provide much more information.

**Comment by ildar** [comment]
Yep, me exactly

**Comment by stephengeorgewest** [comment]
No, my bootloader is locked... Using amazon's build, 7.1.1, kernel version 3.10.49

**Comment by ildar** [comment]
I wonder if emulator would reproduce

**Comment by avuton** [comment]
@ildar: I tried to find a recent Arm Android AOSP image to test that after this bug closed, I couldn't any.

**Comment by relan** [comment]
I checked the APK built by F-Droid: armv7 libraries contain text relocations that are [prohibited since Android 6.0](https://developer.android.com/about/versions/marshmallow/android-6.0-changes#behavior-runtime). Armv8 builds are not affected.

Could anyone share an APK built by the author? I have no Google Play. I'd like to check native libraries there.

**Comment by ildar** [comment]
Yalp does its work ok: [org.musicpd.29.apk.zip](https://github.com/MusicPlayerDaemon/MPD/files/3101197/org.musicpd.29.apk.zip)

**Comment by relan** [comment]
Thanks.

I was wrong about text relocations: they are the reason of crashes on x86.

The upstream APK crashes on a armv7 device with Nougat in the same way as the F-Droid build.

**Comment by ildar** [comment]
Thanks for looking into it.
Relan, do you have idea how to help to trace the crash point?

**Comment by relan** [comment]
The crash point is saved in the tombstone. You can reproduce the issue in armv7 emulator with Android 7.0, run `adb root` and then pull the tombstone file.

**Comment by ildar** [comment]
I mean help devs to hunt the bug. see
https://github.com/MusicPlayerDaemon/MPD/issues/521#issuecomment-479393152
