### ISSUE TITLE
mixer_type is an optional ALSA output parameter in mpd.conf.5

### ISSUE THREAD

**Issue by crocket** [MusicPlayerDaemon/MPD#552]
https://www.musicpd.org/doc/html/user.html#configuring-audio-outputs tells a different story than mpd.conf.5

**Comment by MaxKellermann** [comment]
[mpd.conf.5](https://github.com/MusicPlayerDaemon/MPD/blob/master/doc/mpd.conf.5#L154-L160) tells you
> See documentation for the **audio_output_format** parameter for more details

That's not a different story, is it? It tells you to read the very user manual you linked to.

**Comment by crocket** [comment]
But, that's documentation for `format <sample_rate:bits:channels>`, not `mixer_type <hardware, software or none>`.

It is confusing.

**Comment by MaxKellermann** [comment]
Sorry, I misread this. True, the manpage is badly written, and this part is in the wrong section. All references to ALSA should probably be removed, because that's just one of many plugins.

btw. there's no such thing as "web documentation". There is one copy of the documentation which comes with MPD on the web server, but that's not exclusive content for the web. That's just one copy of documentation you already got in the MPD source tarball.
