### ISSUE TITLE
Feature request: MPEG-DASH audio support

### ISSUE THREAD

**Issue by danburd** [MusicPlayerDaemon/MPD#560]
This issue is a feature request for [MPEG-DASH](
https://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP) audio support within Music Player Daemon.

> Dynamic Adaptive Streaming over HTTP (DASH), also known as MPEG-DASH, is an adaptive bitrate streaming technique that enables high quality streaming of media content over the Internet delivered from conventional HTTP web servers. Similar to Apple's HTTP Live Streaming (HLS)...

While most DASH streams are video streams, there are some audio-only streams, including from the BBC, which can be found [here](http://www.bbc.co.uk/radio/imda/imda_transports.xml).

If the project maintainers believe that this feature is outside the scope of the project or that demand is insufficient, and consequently close this issue, I will not be offended. Thank you for considering this feature request, and for all of your work on MPD.

**Comment by chsims1** [comment]
Just wondering if anything has changed in the interim with regard to libraries & potential implementation.  BBC radio seems to have heavily invested in the standard, especially since their streaming changes in March 2021.

**Comment by ptorre** [comment]
I was researching DASH support so that I could get this working, but now find that the BBC streams have started working in mpd.  This is on the old distro install of  `Music Player Daemon 0.21.5 (0.21.5)`  on `Raspbian GNU/Linux 10 (buster)`.

I'm wondering if updated libavformat libraries have made this work.
Does anyone know if that is the case or is it possible that the BBC streams are falling back to a non DASH stream on the cdn?

**Comment by danburd** [comment]
DASH appears to work for me too, and I'm just using mpd and ffmpeg from the Fedora repositories without any special build flags. I suppose this issue can be closed.
