### ISSUE TITLE
Add option to save playlists as m3u8.

### ISSUE THREAD

**Issue by Gugli** [MusicPlayerDaemon/MPD#602]
Hello,

In order to achieve greater compatibility, I believe it would be great to have new settings concerning the way playlists are saved. Specifically, be able to save valid m3u8 files. 

If I'm not mistaken, it can be done by
setting PLAYLIST_FILE_SUFFIX to ".m3u8"
writing BOM when saving in SavePlaylistFile (before the for loop)
reading and checking BOM in LoadPlaylistFile

Taking the BOM into account may be considered optional, since big-endian architectures tend to disappear. Discardind big-endian encoded playlists may be a valid compromise.

To ensure compatibility,  MPD should handle both m3u and m3u8 when listing/reading playlists. 

Currently, the saved m3u files are not portable, because m3u files are expected to be encoded in the local machine default encoding. Also, it seems that MPD for Window saves UTF8 encoded m3u files, which is IMHO invalid : files should be encoded in UCS-2/UFT16. Switching to m3u8 files could even make things simpler (no need to fix the windows case : always save in UTF8).

If you think this change is of some value, I'll start working on it and make a pull request.

**Comment by MaxKellermann** [comment]
MPD's `playlist_directory` is not meant ot be portable or compatible with anything or be used by anybody but MPD itself. There's an API to access those playlists.

But.... 
> Taking the BOM into account may be considered optional, since big-endian architectures tend to disappear. Discardind big-endian encoded playlists may be a valid compromise.

This doesn't make sense. There's no such thing as "byte order" in UTF-8. You need a well-defined byte order with UTF-16, but not with UTF-8.

Anyway, your suggestion would create compatibility problems with existing MPD installations, and fixing those would add complexity. But I can't see any justification for this change or the added complexity it requires.

**Comment by Gugli** [comment]
I see your point. Seems sensible.

Concerning BOM, it seems that some music software add it in M3U8 files, even if it's not needed. My mistake.

I find it weird to have chosen ".m3u" as file extension, and a format that matches "M3U" files on UTF8-based OSes (but not windows), if there was no intent to make it standard. But I can understand why things like that happen during a project.

I won't work on that then. :)

Thanks for your input.

**Comment by MaxKellermann** [comment]
When MPD was created in 2003, I guess m3u8 didn't yet exist, and of course, quite a few not-so-perfect decisions were made, just like every project does.
But actually back then, MPD indeed used to use the "ANSI code page" instead of UTF-8 to save file names. That however was a big problem, because the ANSI code page is incapable of representing many Unicode characters, which means MPD loses information. So eventually I got a bug report: https://github.com/MusicPlayerDaemon/MPD/issues/102 and then switched to UTF-8: https://github.com/MusicPlayerDaemon/MPD/commit/9703a401c5ac3f679503b845805fe24db22c458c
On Windows, character encodings have always been confusing. While the rest of the world eventually settled on simply using UTF-8 for everything, Windows started out with UCS-2, because it's so much easier than UTF-8 - having fixed-size characters. Eventually, it turned out that UCS-2 was just as lacking as ISO-Latin, and they decided to migrate to UTF-16 instead of UCS-2, which combines the complexity of UTF-8 with the bloat of UCS-2. Will take another decode or two until Windows has proper UTF-8 support ;-)
