### ISSUE TITLE
ID3 plugin not detected

### ISSUE THREAD

**Issue by Chris56** [MusicPlayerDaemon/MPD#621]
Music Player Daemon 0.19.21
on raspian (debian 9.9)
Linked against the id3 lib:
ldd /usr/bin/mpd|grep id3
	libid3tag.so.0 => /usr/lib/arm-linux-gnueabihf/libid3tag.so.0 (0x73a9f000)
So,
mpd is compiled with id3 support, successfully linked against libid3tag and the libid3tag does exist on the system.
However,
mpd --version
does **NOT** show the line: Tag plugins:
(and consequently not id3tag)
And -as a result- the tag db does not contain any of the id3 tags.

**Comment by MaxKellermann** [comment]
Your MPD version is very old and unsupported.

**Comment by Chris56** [comment]
I don't think it wise to close this bug just because it is based on a non recent version.
The quality of this bug does have general interest, which might reveal problems also with recent versions, namely: how come a successful compilation and linking again the proper library (and it is being referenced by the executable!!!) does not show up in "--version" nor does it seem to be executed.
I'm NOT talking about: why is a certain tag not being recognized or anything similar.
AND: I cannot think of a flag in mpd.conf that prevents id3tags (given a local database). But with this I may be wrong.

**Comment by MaxKellermann** [comment]
I do think it's wise. Of course, you may think whatever you want, and you may question my refusal to even look at any bug report about an old version. But I decide what I spend my time on.
Maybe our disagreement leads to motivating you to help with developing MPD, and then you can spend time on researching (bogus) bug reports on old versions.
As long as no volunteer exists who wants to work on your bug report, it will be closed, even if that makes you unhappy.

Btw. if I wanted to argue with you, we could talk about why you deleted the bug reporting template, demonstrating your refusal to provide enough information. I could explain that "ldd" is not a tool showing whether MPD was linked with libid3tag. Going deeper, I could explain that the whole build system of MPD was completely rewritten after version 0.19, and if there ever was a bug, it would most likely not be present anymore today. And that MPD 0.19 did not even have code which printed the availability of ID3 support in "--version", so this conclusion of yours was wrong as well.

Almost everything in your bug report was wrong. That's not a big problem - I have to deal with such things every day, that's what happens when you manage a popular open source project. Just don't pretend that you're wiser.

**Comment by Chris56** [comment]
a) Not knowing whether the "template" was a recommendation or a must, I had read other reports to check on the layout prior to reporting. The ones I randomly picked did not follow the - what I by then concluded- recommendation.
I think this was a reasonable way to deal with the decision whether "template" was a must or a recommendation.
b) Concerning ldd: I did check whether it was actually an unused reference. Again, I found this a readonable way to deal with ldd. However, there are definitely very many other things, that I don't know about ldd.
c) Had I known mpd's build system had been rewritten, I wouldn't have reported anything (as I - at a first glance - supected something in the build process and may be worth reporting). Again, I thought a reasonable way to deal with it.

Participating in the development of mpd (responsible for reading bogus reports) wouldn't be wise, as I obviously cannot live up to your intellectual standards. Contributions by me would most likely result in being insulted for my limited capabilities as can be seen by my unsatisfactory reasoning above.

Therefore, I will not hassle you again.
