### ISSUE TITLE
Support of SACD ISO images in mpd

### ISSUE THREAD

**Issue by mistepien** [MusicPlayerDaemon/MPD#644]
## Feature request
It would be great to merge code or functionality from:
https://github.com/archphile/mpd-manisiutkin

This is about supporting the SACD iso images.

**Comment by MaxKellermann** [comment]
This repository cannot be merged for formal reasons, because it isn't a fork of the MPD git repository - it doesn't contain any commits which can be merged, technically. Any changes in the code would need to be identified manually and copied manually. No, thanks.

But I happen to know this MPD fork. The author tried to get the feature merged into MPD many years ago, but his code failed the review. Instead of fixing it, he decided to continue to maintain his code as an independent fork. Now it's many years later, the code is still in extremely bad shape, and still doesn't meet the quality requirements to be merged into the MPD repository.

This kind of feature would be useful for MPD, but there appears to be nobody willing to do it properly. Pull request welcome for good code, but this is not. Sorry.
