### ISSUE TITLE
About MAX_BINARY_SIZE constant 

### ISSUE THREAD

**Issue by epicfrequency** [MusicPlayerDaemon/MPD#682]
Currentli using MaximumMPD as client to MPD. It utilize the file command to pull album art via MPD. 

I have experienced slow and broken album art down loading using it.  Did a few trial and error test. 

Figured the client does not like big album art file, even 500KB file may get it stuck. I have solved it by resizing all my album art to less than 100kb, not a great solution. 

However from rbackhouse's hint below, I tried changing MPD source code 's MAX_BINARY_SIZE from 8192 to 1048576,  the MaximumMPD works great now, even with bigger than 4MB album arts. 

My question is ,  should MAX_BINARY_SIZE be bigger than 8192, or what is the better size for it?

Thank you. 

MaxmumMPD issue below for reference:
https://github.com/rbackhouse/MaximumMPD/issues/17

rbackhouse commented 13 hours ago
TBH the albumart API in MPD is not really going to work speedily with large albumart files. It doesn't provide a true streaming API. The MPD server decides the chunk size and from what I have seen that is typically 8k. For a 512k file that will be 64 calls for a single file.

**Comment by MaxKellermann** [comment]
What is this issue about - slow downloads or broken downloads?
If you experience broken downloads, we're talking about a bug. Before we do anything else, we should solve this.
Because if enlarging the limit makes the symptom disappear, this means we just found a lousy workaround, but the bug is still lurking there.
After the bug is fixed, we can talk about how to speed up transfers.

So my suggestion is: if you believe the "broken downloads" thing is a MPD bug, write a proper bug report with information on how to reproduce it. After that is fixed, we may reopen this one.
