### ISSUE TITLE
MPD not using libid3tag for tag reading, but claims it does

### ISSUE THREAD

**Issue by uqs** [MusicPlayerDaemon/MPD#694]
### Describe the bug
MPD doesn't know about the new ID3v1 tag genres numbered 148--191. It uses libid3tag which also doesn't know about them. So I added them to libid3tag and recompiled everything and MPD still only shows these genres as "(152)" instead of the actual text.

## Expected Behavior
Show genre 152 as "Big Beat", not (152). Actually use libid3tag to parse the tags. After wasting an afternoon and finding issue #82 it became clear that mpd seems to use ffmpeg for the tag reading, not libid3tag. So the output of mpd --version seems to be lying.

## Actual Behavior
It uses ffmpeg to read the tags (and I haven't patched _that_ yet).
If libid3tag is not used, I would strongly suggest to remove it altogether. It is old and unsupported and actively misleading.

## Version

% ./mpd --version
Music Player Daemon 0.21.16 (0.21.16)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple

Storage plugins:
 local

Decoders plugins:
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [pcm]

Filters:

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe oss httpd recorder

Encoder plugins:
 null vorbis lame wave flac

Archive plugins:
 [bz2] bz2

Input plugins:
 file archive curl ffmpeg

Playlist plugins:
 extm3u m3u pls xspf asx rss flac cue embcue

Protocols:
 file:// http:// https:// gopher:// rtp:// rtsp:// rtmp:// rtmpt:// rtmps://

Other features:
 icu ipv6 tcp un

**Comment by MaxKellermann** [comment]
MPD uses libid3tag only if the decoder plugin doesn't have a native tag handling mechanism. For example, the `mad` and `mpg123` decoders (for MP3 files) can't read tags, so MPD falls back to libid3tag (or APE tags, whatever kind of generic tags is present).

Your bug report doesn't say what kind of files you're trying to read, so I can't verify anything.

But if MPD uses FFmpeg for those files, it won't use libid3tag, because the FFmpeg library already has a native tag reader, and there's no need to fall back to libid3tag. This works as designed!

> It uses ffmpeg to read the tags (and I haven't patched that yet).

That's how it's supposed to work.

> If libid3tag is not used, I would strongly suggest to remove it altogether.

You can disable libid3tag support at compile time with the flag `-Did3tag=disabled`.

**Comment by uqs** [comment]
Is mad/mpg123 still widely used? Isn't ffmpeg always the superior option given the wider supported formats?

Anyway, it's about files with ID3v1 tags with genre > 148, so you could take any of those, but it's MP3s in my case (not sure any other format supported ID3v1?)

See https://en.wikipedia.org/wiki/List_of_ID3v1_Genres for the list of additions made by WinAMP.

I find it puzzling that no one seems to have reported this genre issue, so far.

Could you add least at "ffmpeg" as a "Tag plugin", preferably listed before id3tag. While this might be obvious to you, as a user if only id3tag gets listed there, I would assume the tags come from there (though how it would read non-id3 tags would then still be a mystery)

**Comment by MaxKellermann** [comment]
> Is mad/mpg123 still widely used? Isn't ffmpeg always the superior option given the wider supported formats?

Does it really matter if it's widely used? MPD supports all of those options, and leaves the decision up to you.
FFmpeg has pros and cons, and it's very reasonable to decide not to use it. You decided to use it, that's fine.

> Anyway, it's about files with ID3v1 tags with genre > 148, so you could take any of those, but it's MP3s in my case (not sure any other format supported ID3v1?)

Which is a proprietary extension created by single commercial firm, not a standardized community-agreed design. If you want MPD to understand it (in your configuration), ask the FFmpeg project for support.

> Could you add least at "ffmpeg" as a "Tag plugin", preferably listed before id3tag.

No, because it's not a "tag plugin".
