### ISSUE TITLE
find modified-since with different versions of satellite and proxy

### ISSUE THREAD

**Issue by geneticdrift** [MusicPlayerDaemon/MPD#742]
When mpd version 0.21.18 is satellite with proxy mpd version 0.20.21
the find command is sent to the proxy without the arguments:

### satellite 0.21.18 log:
<pre>
client: [5] process command "find modified-since 1580127938"
exception: too few arguments for "find"
client: [5] command returned 3
client: [6] process command "find "(modified-since '578134866')""
exception: too few arguments for "find"
client: [6] command returned 3
</pre>

### proxy 0.20.21 log:
<pre>
client: [0] process command "find"
client: [0] command returned 2
client: [0] process command "find"
client: [0] command returned 2
</pre>

**Comment by MaxKellermann** [comment]
MPD 0.20.x is not supported.

**Comment by geneticdrift** [comment]
Would it be appropriate to change `ProxyDatabase::Connect()`:
<pre>
diff --git a/src/db/plugins/ProxyDatabasePlugin.cxx b/src/db/plugins/ProxyDatabasePlugin.cxx
index 6d77416f2..fdecc11ec 100644
--- a/src/db/plugins/ProxyDatabasePlugin.cxx
+++ b/src/db/plugins/ProxyDatabasePlugin.cxx
@@ -493,8 +493,8 @@ ProxyDatabase::Connect()
    try {
        CheckError(connection);
 
-       if (mpd_connection_cmp_server_version(connection, 0, 19, 0) < 0)
-           throw FormatRuntimeError("Connect to MPD %s, but this plugin requires at least version 0.19",
+       if (mpd_connection_cmp_server_version(connection, 0, 21, 0) < 0)
+           throw FormatRuntimeError("Connect to MPD %s, but this plugin requires at least version 0.21",
                         mpd_connection_get_server_version(connection));
 
        if (!password.empty() &&

</pre>

**Comment by fabsmusicjunkie** [comment]
I'm also having a problem with both running mpd 0.21.x

The host is running 0.21.10  and the satellite 0.21.22

Satellite Log 0.21.22
Jul 10 22:55 : client: [57] process command list returned 0
Jul 10 22:55 : client: [57] process command "find "(modified-since '1591822336')""
Jul 10 22:55 : exception: Failed to parse time stamp
Jul 10 22:55 : client: [57] command returned 2
`
Host Log 0.21.10
`client: [9] process command "find "(modified-since \"2020-06-10T20:52:16Z\")""                                                              
client: [9] command returned 2              
`
There is an error that the date-format seem to change between the satellite and the host.
