### ISSUE TITLE
input from named pip/fifo

### ISSUE THREAD

**Issue by markfoodyburton** [MusicPlayerDaemon/MPD#852]
Hi, I'm not sure if this is supposed to work, 
I've been trying to play a stream from a named pipe (generated by Shairport-sync in my case, hence generating a 44100 PCM). 

I tried the obvious
`mpc add file://my_fifo`
(where my_fifo sits in my music directory)

If not, this would be a convenient feature...

**Comment by MaxKellermann** [comment]
This doesn't work because MPD will only read regular files, and even if it would be willing to play a pipe, it wouldn't know the audio format delivered there, and the whole idea of using raw PCM on a pipe is very fragile.
This could be implemented (in a fragile way). Doing this would be rather easy, but I'm not convinced that this is a good idea, therefore I won't spend time on it. But I'm willing to give advice to somebody who wants to give it a try.

**Comment by markfoodyburton** [comment]
Thanks for the info. In the end, I think pausing MPD is a better approach anyway in my case. Thanks again.

**Comment by matejdro** [comment]
For me, pausing MPD is not a feasible alternative as MPD is the server that streams the music to the rest of the speakers. So sending music from Shairport to MPD is kinda necessary.

Allowing format specifying, similar to how it's done for alsa plugin would not be that fragile (not any more fragile than alsa, which is also raw):

`mpc add file://my_pipe?format=44100:16:2`
