### ISSUE TITLE
Is gapless playback supported when acting as icecast source?

### ISSUE THREAD

**Issue by coolaj86** [MusicPlayerDaemon/MPD#936]
## Question

Does MPD work as gapless icecast2 source? What needs to be enabled to do so? What file formats are supported?

## What I've Tried

I've been searching high and low but I can't find any way to get `mpd` to act as a gapless icecast source.

I've tried m4a, mp3, ogg, and raw WAV, but it seem that there's always either a click or a gap.

I have been able to test with vox and mopidy => icecast2 => vlc, so I know that my files are gapless and I know that they can be streamed via icecast2.

I've used the instructions to compile the latest version from source on Ubuntu 20.x and looked through the config file to turn on the gapless decoder option, but to no avail.

**Comment by MaxKellermann** [comment]
This has nothing to do with the output plugin you use. This is only about decoder plugins. Most decoder plugins attempt to cut away the codec pre-skip.
The "mad" decoder plugin used to have an option to do gapless playback, but that option has been removed, and the plugin always does gapless.
If you have problems, write a detailed bug report. Your text here has no usable information.

**Comment by solderjs** [comment]
> This has nothing to do with the output plugin you use.

My source files are WAV and I'm getting different results in the same VLC client and same icecast server with different icecast source clients (i.e. MPD, Modipy, Liquidsoap), and even different results depending on which format (i.e. Ogg vs Mp3) I choose as the encoded output, so that does not seem to hold true in practice.

> Your text here has no usable information.

I guess that depends on whether or not the person on the other end.

What kind of information are you looking for?

## My Setup

I've tried with both Ubuntu 18.04 which has mpd 0.20.18 as well as Ubuntu 20.04 which has a janky segfaults-all-the-time version, so I had to build v0.21.25-1043-gdf1bf28ca from source.

My mpd config looks a bit like this:

`/etc/mpd.conf`:
```txt
decoder {
        plugin "hybrid_dsd"
        enabled "yes"
        gapless "yes"
}
audio_output {
	type		"shout"
	encoder		"vorbis"		# optional
	name		"My Shout Stream"
	host		"localhost"
	port		"8000"
	mount		"/stream"
	password	"hackme"
	bitrate		"128"
	format		"44100:16:1"
	protocol	"icecast2"		# optional
	description	"My Stream Description"	# optional
}
filesystem_charset "UTF-8"
```

The actions I took to create the stream were a bit like this:

```
rsync -av ~/test-music/ /var/lib/mpd/music/
mpc add test-part1.wav
mpc add test-part2.wav
mpc add test-part3.wav
mpc add test-part4.wav
mpc repeat
mpc play
```

The playback is not gapless even though it _should_ be encoding directly from the gapless wav files as a single gapless stream as if it had all come from a single wav file.

As stated previously, the wav files themselves play gaplessly in Vox, and apparently in Liquidsoap, but only when encoded as mp3, not when encoded as ogg.

**Comment by MaxKellermann** [comment]
To reproduce, I need your WAV files.
Do you hear gapless when you use a different output plugin, like ALSA?

**Comment by solderjs** [comment]
I'm running this on Digital Ocean, so there is no sound card.

In fact, I don't think I was actually able to get the most recent version from git to run because it kept erroring out with something about gstreamer that I didn't understand how to disable.

These ~15 second tone test files are randomly split every <2 seconds:

[chirp-220hz-2200hz.tar.gz](https://github.com/MusicPlayerDaemon/MPD/files/5089764/chirp-220hz-2200hz.tar.gz)
[tone-split-rand.tar.gz](https://github.com/MusicPlayerDaemon/MPD/files/5089765/tone-split-rand.tar.gz)

They play perfectly gaplessly with Vox and VLC locally (no clips, pops, gaps, etc), and also via icecast using liquidsoap as an mp3 or m4a source to VLC.

**Comment by coolaj86** [comment]
Thank you!

I haven't tested this yet, and it looks like I've already got a solution for production with `liquidsoap`, but I'm so glad to see this make it in and I look forward to trying for myself.
