### ISSUE TITLE
using APE replaygain instead of lame replaygain

### ISSUE THREAD

**Issue by xpilgrim** [MusicPlayerDaemon/MPD#94]
In some tests I think, that I've figured out that MPD prefer to use for mp3 loudness control the lame replaygain value and is ignoring the APE replaygain data. I would like to ask to change this behavior to prefer the APE replaygain data for playing. 

Or is it possible to add a switch in the mpd.conf to disable reading lame replaygain?

Why?
IMHO is the lame replay gain rarely used "in the wild". So it could lead to ugly results (see below). Furthermore I don't know a tagger or editor (except ffmpeg) that display the lame replaygain for analysis. So the user can mislead to think, there is no lame replaygain. If a user apply special replaygain values with a "normal" replaygain editor, I think, MPD will never use this APE replaygain data. Thats very confusing!

If the file has:
-  (lame replaygain) AND (replaygain APE Tag): MPD uses the lame replaygain, but ignore possible different or special set replaygain APE data

-  (lame replaygain) AND ("hardcoded" mp3Gain) wich result in additionally present APE replaygain undo data: MPD reduces the "m3gain-reduced" file additionally with lame replaygain. That leads to playing the file too quiet!

See screenshots with jack and EBU meter
![lame_ape_replay_gain_comparision](https://user-images.githubusercontent.com/2353879/29112273-a84d9b7a-7ced-11e7-82c6-6cde6f4d1cdf.png)

**Comment by MaxKellermann** [comment]
> the lame replay gain rarely used "in the wild"

If it's not used, then MPD will not use it as well, and use APE tags instead.
Is your request about ignoring bogus data in broken files? Or what is really the problem?

**Comment by xpilgrim** [comment]
While the lame replaygain is often not read/displayed by using such editors e.g. mp3gain, I mean, i'ts not only me that tought, there is no lame replaygain in that files. So I've many mp3 files with "wrong" or unnecessary lame replaygain AND APE replaygain. Until now, I know not way to remove the lame replaygain without reencoding...did you?

**Comment by MaxKellermann** [comment]
You did not answer my question, but my interpretation is that you want MPD to ignore the Lame tag because it contains bogus data.
No, this is completely not MPD's fault, and it's not MPD's fault that your tools are inadequate for fixing your broken files.
Changing the priority of tag types will not fix the problem - it will only make it disappear for some of your files, and that's not a good solution. The only solution is to remove/replace bogus data from your files.

**Comment by xpilgrim** [comment]
I think, one cannot say it's bogus data! That's depending on the point of view! 

If one encode with lame in mp3 and don't set the --noreplaygain option, lame will write a correct replaygain. 

After that, one edit this file with mp3gain, this will add the replaygain in APE but does NOT remove the lame replaygain. The user is not informed about the presence of lame replaygain! Depend on the options for replaygain, the lame replaygain may be ok or bogus in the view from APE replaygain. But I think, nevertheless you can say in generally, its bogus data! 

I think, it is a good behavior, when MPD is first seeking the APE Tag and if present using this instead of an additionally lame replaygain.

**Comment by MaxKellermann** [comment]
Your file has ReplayGain data which you don't want to be used by any software. That's what I call "bogus". Call it something else, but the data is there, but should not be used.
There are three ways to fix this:
a) LAME should not write those tags
b) mp3gain should override those tags because mp3gain's tags obsolete the existing tags
c) MPD should be changed
As you see, three programs are involved in the whole thing, and for whatever reason, you chose to direct your request at MPD. I have no idea why, because MPD behaves correctly according to its design.
There's a file with ReplayGain data, and MPD uses that. MPD cannot know which kind of ReplayGain data to use, so it behaves according to its designed rules, which do make sense (use the data at the lowest possible and most native level, falling back to generic data). But MPD's choice just happens to make you unhappy, but changing it may make others unhappy, because other people may for whatever reasons prefer to use LAME ReplayGain tags. Whatever MPD chooses, half of the population will believe it's wrong.
But the only wrong thing here is that your files have those LAME tags at all. Which leaves (a) and (b) to complain to.

**Comment by xpilgrim** [comment]
OK, thanks for your statement. I will find a way to deal with. But ;-) it could be a nice feature for MPD if the user can decide, what replaygain tags he want to use and decide what fallback chain is the best use case...regardless, MPD is a great solution!
