### ISSUE TITLE
Deduplication

### ISSUE THREAD

**Issue by vext01** [MusicPlayerDaemon/MPD#969]
Hi,

Long-time mpd user. It's great thanks.

I mostly buy music from bandcamp these days, and I download albums in ogg vorbis format (for on the go on my phone) and flac (for elsewhere).

This means that when I import music into MPD, clients display tracks twice. E.g. (in ncmpcpp):
![image](https://user-images.githubusercontent.com/604955/94791395-13c53a80-03c7-11eb-9b3f-0fd7c1054151.png)

One solution might be to restructure my collection such that mpd only looks at flac files, however, some albums I have only in vorbis, others only in mp3.

So how about a feature where the user defines an ordering on their preferred formats, and in the face of duplicates, only the "most preferred" format is imported into the db?

For example, if the ordering is `[flac, ogg, mp3]` then:
 - If a track is available in flac and ogg, only the flac version is imported.
 - If a track is available in ogg and mp3, only the ogg version is imported.

What do you think?

**Comment by MaxKellermann** [comment]
This sounds easy, but is extremely difficult to get right.
Because, how exactly shall MPD detect duplicates? What if one copy is an album re-release with different ordering or bonus tracks? What if one is a re-release of a different recording? (e.g. live, acoustic, remix)

I'm not fond of letting MPD auto-ignore certain files. A user interface (i.e. the client) could have an option for hiding duplicates based on some rules, but the server should always give a full set of choices.

**Comment by vext01** [comment]
Good point, well made.
