### ISSUE TITLE
Snapcast integration

### ISSUE THREAD

**Issue by jplitza** [MusicPlayerDaemon/MPD#975]
[Snapcast] is a software to play time-synchronized audio on multiple computers on the network. This makes it very attractive for multi-room MPD setups.

[Snapcast]: https://github.com/badaix/snapcast
 
Currently, you have to set up a Snapcast server and stream audio to it via FIFO. @MaxKellermann originally posted in #876:

> Snapcast uses MPD's experimental "fifo" output with all its weaknesses. That's a rather bad choice.
> Now if Snapcast had a documented protocol, MPD could implement a "native" Snapcast output plugin without all the "fifo" trouble.

Well, [the binary protocol is documented by now](https://github.com/badaix/snapcast/blob/master/doc/binary_protocol.md), so this issue is basically asking to implement a Snapcast output plugin, that replaces the Snapcast server and lets the Snapcast clients connect directly to MPD.

However, the big challenge is to properly integrate this with MPD's concept of outputs. Currently, Snapcast clients connect to the Snapcast server and can be "managed" there, meaning

* Renaming
* Grouping
* Selecting input stream for groups
* Muting
* Setting volume per client/group

The most natural integration would be if every client was considered its own output by MPD. Then grouping and selecting input streams per group would correspond to partitions in MPD, and muting would correspond to enabling/disabling. But AFAICS, there currently is no concept of such "dynamic" outputs in MPD that can appear and disappear during runtime. (For volume control per output, see #434)

My current workaround is to manually create null outputs in MPD and synchronize their enabled state to the muted state of Snapcast clients via a script: https://github.com/jplitza/mpd-snapcast-sync

BTW, if there are alternatives to set up a WiFi-based multi-room audio setup with precise timing using Raspberry Pis, I'm interested too. But I haven't seen anything that works nearly as good as Snapcast in that regard.

**Comment by MaxKellermann** [comment]
The protocol documentation is incomplete - it does not specify endianness.

**Comment by jplitza** [comment]
> The protocol documentation is incomplete - it does not specify endianness.

True, and other issues with the protocol documentation may arise, since the item on the [roadmap](https://github.com/badaix/snapcast/blob/master/README.md#roadmap) isn't checked yet either.

The purpose of this issue was more to get an idea if the dynamic output idea is realistic. Because without it, integrating Snapcast closer into MPD doesn't yield any benefits, and I can just continue using the FIFO to pass audio between them.

**Comment by skidoo23** [comment]
+1

@jplitza> snapcast supports alsa loopback now.

**Comment by jplitza** [comment]
> @jplitza> snapcast supports alsa loopback now.

Actually, I don't have any problems with the FIFO output. In fact, I prefer it over ALSA loopback, which requires to loosen my `PrivateDevices=true` systemd setting on MPD, and produced audio hickups in a short test. It's just that I've read in other issues that it supposedly is "bad" (even though MPD's documentation doesn't say anything negative about it)

**Comment by badaix** [comment]
I'm using MPD -> FIFO -> Snapcast for many years 24-7 (and while typing this line) without any issue. 
Big thanks to the MPD developers!
BTW: Snapcast protocol is using little-endian, I will add this to the docs.

**Comment by jplitza** [comment]
@badaix So since you found this issue and use MPD yourself: What do you think of the proposal to integrate the Snapcast protocol into MPD? I proposed this not only to avoid using FIFO, but to have a tighter integration, and I'd be interested in your thoughts on that.

**Comment by badaix** [comment]
I think it doesn't make sense to reimplement the Snapcast server protocol in MPD so that clients could directly connect to MPD as a Snapcast server. The idea behind Snapcast is that several audio sources (MPD being one of them) can be routed to different groups, each serving audio to a set of clients. 
What would make sense is to keep MPD as an audio source and for tighter integration, provide a Snapcast-client library, that ...
1. would handle the connection to the Snapserver, including meta data, such as name of the source
2. has an interface comparable to other audio APIs (open with some sampleformat (like 48000, S16_LE, 2 channels) and some audio write function or requesting callback)
3. can be fed with meta data
4. ...

And configure it in `mpd.conf` like
```
audio_output {
    type            "snapcast"
    name            "MPD"
    host            "192.168.0.23"
    port            1790
    format          "48000:16:2"
    mixer_type      "software"
}
```

But there is no such lib yet...

**Comment by kingosticks** [comment]
I've only had a very quick look at this it doesn't look like there is any way to configure groups with this. Is there always just a single group for all clients?

Is there a plan to also support the [JSON-RPC API](https://github.com/badaix/snapcast/blob/master/doc/json_rpc_api/v2_0_0.md)? Obviously you couldn't use it to change the stream since presumably there is only ever a single stream (which fundamentally makes this integration uninteresting for many, as @badix mentioned) but for volume control, muting, adjusting latency etc?

**Comment by MaxKellermann** [comment]
Groups are not part of the binary protocol, thus they are not supported.
There's no plan to support JSON-RPC API (I don't have any). Much of that API doesn't make sense for MPD, because MPD is not a generic Snapcast server, but one that specifically streams MPD's audio output to connected Snapcast clients.

**Comment by jplitza** [comment]
Wow, I'm baffled you just went ahead and implemented this! Thank you so much, @MaxKellermann! Hope I'll get around to test it soon.

**Comment by GK-774** [comment]
Is this supposed to work already (mpd 0.23.12)?
The documentation says "zeroconf yes|no" which apparently is not implemented ("config: option 'zeroconf' on line 149 was not recognized") and the Android Client does not find the Server so I configured it manually and got "error connection reset".
With the conventional snapcast server the Client finds it, connects and plays without issues.

**Comment by MaxKellermann** [comment]
> config: option 'zeroconf' on line 149 was not recognized

This means you built your MPD without Zeroconf support.

**Comment by GK-774** [comment]
Ok, yes that´s correct (have disabled it because with systemd it does not work, I recall vaguely this was discussed somewhere here). Anyway, the Snapcast Android client can´t connect (while it can to a snapcast server on the same machine).
