### ISSUE TITLE
Incorrect Opus replay gain correction

### ISSUE THREAD

**Issue by p10s** [MusicPlayerDaemon/MPD#976]
### Describe the bug
In the method MPDOpusDecoder::HandleTags (OpusDecoderPlugin.cxx) rgi.track.gain and rgi.album.gain are initialized with a +5dB correction. But this correction should only be applied if the corresponding R128 gain tag is actually present in the Opus file. Otherwise sound will be amplified by +5dB when replay gain is enabled and the R128 gain tags are missing.

## Version

0.22

**Comment by p10s** [comment]
I now see that I missed a situation where the +5dB correction applies. If both R128 gain tags are missing, but output_gain is set (non-zero), then the +5dB correction should be applied.

**Comment by MaxKellermann** [comment]
I don't understand. You wrote:
> output_gain is set (non-zero)

The `output_gain` is *always* set. It is a signed 16 bit integer in the range -32768 to 32767, and 0 is a legal value. Why do you believe it should be special?

Under which exact circumstances do you believe the +5dB should be applied, and when not?

**Comment by p10s** [comment]
By 'unset' I meant not set by a loudness tool like r128gain. An output_gain value of zero isn't special, but combined with missing R128 gain tags indicates that the Opus file hasn't been processes by a loudness tool. Adding 5dB in this situation is dangerous because you don't know if loudness normalization has been applied in the encoded audio. It could easily cause distortion (that's what I noticed when I started using v0.22).

I think that the +5dB correction should be applied when output_gain is non-zero or when one of the R128 gain tags is present in the Opus file. Unfortunately, this doesn't cover the situation where the loudness normalization has been applied prior to encoding. A safer alternative might be to change the reference level of replay gain to the EBU R128 standard (by subtracting 5dB of the REPLAYGAIN gain tags value).

**Comment by MaxKellermann** [comment]
First you say output_gain zero isn't special, but then you want to make it a special case. That's not consistent, because it is perfectly possible that an Opus file does not have R128 values but has a zero gain.
I think we still don't know what really the root cause of the problem is. 
Your solution still isn't consistent, because while it may fix one use case, it breaks another. No matter what I do, one or the other group of users will complain. Something is wrong with this.
Maybe, maybe, we should only apply the +5dB offset if there is R128? I don't know enough about this to decide. Who does? @awused?

**Comment by awused** [comment]
I don't think anyone can really speak confidently, not even the author of the spec. An opus file with a 0dB output_gain setting is indistinguishable from one where it has been set, and output_gain is often used on its own for replaygain since the r128 tags were added in a later revision.

As far as I'm aware there's no sure test for determining if an opus file has been scanned for replaygain and scanning tools will behave differently depending on when they were written. For what it's worth the current versions of the two tools I actively use (loudness scanner and the default settings of the one built in to foobar) do set the r128_gain tags explicitly to 0 while using output_gain for replaygain. The presence of an r128_track_gain/r128_album_gain tag - regardless of value - or a non-zero output_gain tag is probably a reasonable heuristic for determining if a file has been scanned. At least I can't think of anything better.

**Comment by p10s** [comment]
I've thought about the problem again and I now think that it's better to keep the current implementation. I'm choosing consistency over making an exception for Opus files that probably already sounded too loud. It's not perfect, but the Opus file design doesn't provide a better solution.

I'm closing this bug, thanks for your time and input.

**Comment by giddie** [comment]
Could you help me find a little clarity regarding this behaviour? I've been experiencing distortion in my Opus files (ripped from CD, encoded with `opusenc`). I've not applied any ReplayGain (mainly because I forgot), but I did have `replaygain=auto`, set from Cantata, and the distortion goes away when it's disabled. Should I really be expecting distortion in this case? Is the only solution to turn off replaygain or tag the files? It's certainly a shame if no more robust solution is possible :(

**Comment by awused** [comment]
I wish there were a good way around it, but there's nothing in an opus file to unambiguously indicate whether it has been scanned with replaygain or not. The gain value in the header is always there, 0 is a valid value for gain, and the r128 tags were added in a later version of the spec and aren't consistently used. Right now the MPD behaviour is about as good as it can reasonably get: ignore the gain setting when replaygain is turned off but assume any opus file is targeting the r128 reference volume when replaygain is enabled. Anything more would just be guessing.

The third option is to convert them to a different format, or re-rip them, and I'd honestly recommend against opus when you have a choice of formats. How efficient the encoding is matters a lot less for local files compared to internet streams, and this gain issue isn't the only problem with the opus container.

**Comment by giddie** [comment]
This is interesting. So if I understand correctly, there's a replaygain offset that means that a header gain value of 0 actually results in a volume boost, which results in the clipping?

I'm also curious about what other issues exist for the Opus container? My understanding is that it's essentially an Ogg container. I previously used Vorbis for ripped music, but switched to Opus as it has overtaken Vorbis as the flagship open audio codec.

**Comment by awused** [comment]
Replaygain targets one volume and the EBU R 128 standard specifies a different one, and the opus spec mandates EBU R 128, so when replaygain is enabled it's necessary to boost opus tracks from the r128 volume to the replaygain volume. All the scanners I've encountered will use the replaygain volume except when tagging opus tracks, where they'll use r128's volume, even the ones that otherwise use the r128 algorithm.

Another issue with opus is that even when the spec was updated to allow some "normal" replaygain/r128 tags, it didn't allow all of the standard ones. I'm not sure how much this affects playback. All audio is also resampled to 48khz (or 24khz/16khz/etc) which is an odd limitation even if it should never cause problems with a decent resampler. I'd just stick to any old lossless format when ripping things.
